### ISSUE TITLE
CLI: sanity dataset import fails on missing metadata

### ISSUE THREAD

**Issue by good-idea** [sanity-io/sanity#1275]
**Describe the bug**

I'm running `sanity dataset export production && sanity dataset import production.tar.gz staging --replace` to sync my production dataset to my staging dataset.

One of my images is missing some metadata. During the `import`, this image throws an error and the whole process is stopped:

```
✔ Exporting documents... (66/66)
✔ Downloading assets... (643/643)
✔ Adding assets to archive...
✔ Clearing temporary files...
Export finished (5m 28.8s)
✔ [100%] Fetching available datasets
✔ [100%] Reading/validating data file (223ms)
✔ [100%] Importing documents (2.47s)
✖ [ 71%] Importing assets (files/images) (46.81s)
o: Failed to upload image @ file:///var/folders/d7/tlsyl3dx2f73v9j7ght57cqm0000gn/T/sanity-import/production-export-2019-04-19t20-36-52-029z/images/542138d111351763702ad45995e5737409c13278-2192x2852.png:
Bad Request - Invalid image, could not read metadata
    at onResponse (~/Sites/myproject/myproject.com/node_modules/@sanity/cli/bin/sanity-cli.js:6489:535)
    at t.(anonymous function).reduce (~/Sites/myproject/myproject.com/node_modules/@sanity/cli/bin/sanity-cli.js:4895:242)
    at Array.reduce (<anonymous>)
    at ~/Sites/myproject/myproject.com/node_modules/@sanity/cli/bin/sanity-cli.js:4895:226
    at ~/Sites/myproject/myproject.com/node_modules/@sanity/cli/bin/sanity-cli.js:4883:919
    at a (~/Sites/myproject/myproject.com/node_modules/@sanity/cli/bin/sanity-cli.js:4883:1028)
    at E (~/Sites/myproject/myproject.com/node_modules/@sanity/cli/bin/sanity-cli.js:4931:1352)
    at u (~/Sites/myproject/myproject.com/node_modules/@sanity/cli/bin/sanity-cli.js:4931:2878)
    at s.<anonymous> (~/Sites/myproject/myproject.com/node_modules/@sanity/cli/bin/sanity-cli.js:2345:181)
error Command failed with exit code 1.
```

**To Reproduce**

You're welcome to give this a try with the same dataset (I just ask that you `import` it into a separate instance). You can DM me on slack for the project info.

**Expected behavior**

I would expect (or hope) that this command would bypass the broken image, and report it as a warning at the end of the command. Or, better yet, find some way to repair the missing metadata.

**Which versions of Sanity are you using?**

```
@sanity/cli             0.140.14 (up to date)
@sanity/base            0.140.12 (up to date)
@sanity/cli             0.140.14 (up to date)
@sanity/components      0.140.12 (up to date)
@sanity/core            0.140.12 (up to date)
@sanity/default-layout  0.140.14 (up to date)
@sanity/default-login   0.140.15 (up to date)
@sanity/desk-tool       0.140.14 (up to date)
@sanity/image-url       0.140.12 (up to date)
@sanity/vision          0.140.14 (up to date)
```

**What operating system are you using?**

Mac OS

**Which versions of Node.js / npm are you running?**

```
6.9.0
v10.5.0
```

**Comment by good-idea** [comment]
Update: removing the image from the archive and running another import:

```
✔ [100%] Fetching available datasets
✔ [100%] Reading/validating data file (211ms)
✔ [100%] Importing documents (3.13s)
✔ [100%] Importing assets (files/images) (4m 6.79s)
✔ [100%] Setting asset references to documents (1m 2.05s)
✖ [  0%] Strengthening references (1m 3.61s)
{ description:
   'The mutation(s) failed: Document "75ae29f2-ae4a-4cc6-8e28-497d69f46567" references non-existent document "image-8be2417d05251ea829460de2f237dcc20497e5a8-1752x1275-jpg"',
  items: [ { error: [Object], index: 1 } ],
  type: 'mutationError' }
error Command failed with exit code 1.
```

I'm able to do what I need to do with this import, though - so it's not anything urgent or bothersome for me.

**Comment by onetwothreebutter** [comment]
I'm running into this issue too! I'll try updating my CLI though.

**Comment by kmelve** [comment]
Confirmed as a bug, we'll take a closer look at it. Stay tuned!

**Comment by bjoerge** [comment]
I believe this was fixed in [v0.140.20](https://github.com/sanity-io/sanity/releases/tag/v0.140.20). Could you try upgrading and check if the issue still persists?

**Comment by good-idea** [comment]
This is still breaking for me. When I unpack the archive and find the files that cause the issue, they are "broken" ones like this:

![image](https://user-images.githubusercontent.com/11514928/57661085-47b77a00-759e-11e9-8349-924264a658fb.png)

```
$ sanity dataset import kame.tar.gz staging --replace
✔ [100%] Fetching available datasets
✔ [100%] Reading/validating data file (229ms)
✔ [100%] Importing documents (1.57s)
✖ [ 64%] Importing assets (files/images) (21.75s)
o: Failed to upload image @ file:///private/var/folders/d7/tlsyl3dx2f73v9j7ght57cqm0000gn/T/4b5727551e555a1cf5ff9af1fe839648/sanity-import/kame-export-2019-05-13t23-38-51-685z/images/2e979401b96dc1b433547cc7d0fac41828ecf44f-2520x2520.png:
Bad Request - Invalid image, could not read metadata
    at onResponse (~/Sites/hikawa.studio/hikawa.studio/node_modules/@sanity/cli/bin/sanity-cli.js:6483:539)
    at t.(anonymous function).reduce (~/Sites/hikawa.studio/hikawa.studio/node_modules/@sanity/cli/bin/sanity-cli.js:6501:242)
 
```


The image isn't broken in the main dataset - when I explore the files straight from the Sanity dashboard - but appears to have been messed up somehow in the download process.

**Comment by rexxars** [comment]
We have a fix on the way, hang tight. Should be out within a few hours.

**Comment by rexxars** [comment]
Should be fixed in the latest release!

**Comment by ryaninvents** [comment]
I think this has recurred; I'm on `@sanity/cli 2.4.0`

```
-> % sanity -v
@sanity/cli version 2.4.0

-> % sanity dataset import ~/Documents/production-export-2021-02-24t20-10-18-618z staging --replace

✔ [100%] Fetching available datasets
✔ [100%] Reading/validating data file (522ms)
✔ [100%] Importing documents (1.72s)
✖ [  6%] Importing assets (files/images) (8.08s)

o: Failed to upload image @ file:///Users/ryan/Documents/production-export-2021-02-24t20-10-18-618z/images/151c6747b6e255b514965955ad444ac71c570f63-3000x2000.png:
Bad Request - Invalid image, could not read metadata
    at onResponse (~/.local/share/npm/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4180:533)
    at ~/.local/share/npm/lib/node_modules/@sanity/cli/bin/sanity-cli.js:2736:279
    at ~/.local/share/npm/lib/node_modules/@sanity/cli/bin/sanity-cli.js:2724:918
    at ~/.local/share/npm/lib/node_modules/@sanity/cli/bin/sanity-cli.js:2724:1026
    at E (~/.local/share/npm/lib/node_modules/@sanity/cli/bin/sanity-cli.js:2772:1332)
    at ~/.local/share/npm/lib/node_modules/@sanity/cli/bin/sanity-cli.js:2772:2845
    at s.<anonymous> (~/.local/share/npm/lib/node_modules/@sanity/cli/bin/sanity-cli.js:1332:100)
    at A (~/.local/share/npm/lib/node_modules/@sanity/cli/bin/sanity-cli.js:1350:6029)
```

**Comment by rudietuesdays** [comment]
Hi! I'm also receiving this error on a request to upload an image. Having the problem with both `jpg` and `png` files.

A request such as:
```
curl \
  -X POST \
  -H 'Content-Type: image/jpeg' \
  --data-binary "/Path/to/file/<image>.jpg" \         
  'https://<projectId>.api.sanity.io/v2021-03-25/assets/images/<dataset>'
```

Is returning:
```
{"statusCode":400,"error":"Bad Request","message":"Invalid image, could not read metadata","details":"Input buffer contains unsupported image format"}
```

**Comment by ArefEghbaliDev** [comment]
Hi @rudietuesdays , did you find any solution for this problem?

> Hi! I'm also receiving this error on a request to upload an image. Having the problem with both `jpg` and `png` files.
> 
> A request such as:
> 
> ```
> curl \
>   -X POST \
>   -H 'Content-Type: image/jpeg' \
>   --data-binary "/Path/to/file/<image>.jpg" \         
>   'https://<projectId>.api.sanity.io/v2021-03-25/assets/images/<dataset>'
> ```
> 
> Is returning:
> 
> ```
> {"statusCode":400,"error":"Bad Request","message":"Invalid image, could not read metadata","details":"Input buffer contains unsupported image format"}
> ```

Hi, did you find a solution?

**Comment by cemarguvanli** [comment]
I also had this error and I couldn't find a way to solve it. try to run with `--allow-failing-assets` it will skip assets that cannot be fetched/uploaded
