### ISSUE TITLE
Studio CLI dataset export command errors since 1.149.8

### ISSUE THREAD

**Issue by raine** [sanity-io/sanity#1832]
**Describe the bug**

`studio dataset export` command fails after updating `@sanity/core` from `1.149.7` to `1.149.8`.

```
$ .../node_modules/.bin/sanity dataset export staging
? Output path: staging.tar.gz
? File staging.tar.gz" already exists, would you like to overwrite it? Yes
Exporting dataset "staging" to "/studio/staging.tar.gz"
⠧ Exporting documents...Unhandled rejection: TypeError: Cannot read property 'setTimeout' of undefined
    at /node_modules/@sanity/export/lib/requestStream.js:73:31
    at Generator.next (<anonymous>)
    at /node_modules/@sanity/export/lib/requestStream.js:79:10
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/node_modules/@sanity/export/lib/requestStream.js:9:103)
    at _next (/node_modules/@sanity/export/lib/requestStream.js:11:194)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Fixing `@sanity/core` version to `1.149.7` doesn't have this behavior. Latest version also has this bug, but `1.149.8` seems to be where the breakage happens.

Node v13.9.0.

I'll provide more details as requested.

**Comment by rexxars** [comment]
Thanks! This was fixed in 1.149.9!
