### ISSUE TITLE
[Components] Cannot use DefaultAutocomplete component in custom input component

### ISSUE THREAD

**Issue by andrewgadziksonos** [sanity-io/sanity#1942]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

I'm trying to import DefaultAutocomplete from the sanity component library into my custom input component in my studio implementation and I'm receiving the following error,

```
Stack trace:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `DefaultAutocomplete`.
    at createFiberFromTypeAndProps (/static/js/vendor.bundle.js:29008:21)
    at createFiberFromElement (/static/js/vendor.bundle.js:29031:15)
    at reconcileSingleElement (/static/js/vendor.bundle.js:19264:23)
    at reconcileChildFibers (/static/js/vendor.bundle.js:19324:35)
    at reconcileChildren (/static/js/vendor.bundle.js:21795:28)
    at updateHostComponent (/static/js/vendor.bundle.js:22335:3)
    at beginWork (/static/js/vendor.bundle.js:23669:14)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:5197:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:5246:16)
    at invokeGuardedCallback (/static/js/vendor.bundle.js:5301:31)

Component stack:
    in div (created by DefaultAutocomplete)
    in div (created by DefaultFormField)
    in label (created by DefaultFormField)
    in div (created by DefaultFormField)
    in DefaultFormField (created by DefaultAutocomplete)
    in DefaultAutocomplete (created by ContentStringInput)
    in ContentStringInput (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by Field)
    in div (created by Field)
    in Field (created by ObjectInput)
    in div (created by ObjectInput)
    in div (created by ObjectInput)
    in ObjectInput (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by SanityFormBuilder)
    in FormBuilderContext (created by SanityFormBuilderContext)
    in SanityFormBuilderContext (created by SanityFormBuilder)
    in SanityFormBuilder (created by EditForm)
    in form (created by EditForm)
    in EditForm (created by FormView)
    in div (created by FormView)
    in FormView (created by DocumentPane)
    in div (created by ScrollContainer)
    in ScrollContainer (created by Pane)
    in div (created by Pane)
    in div (created by Pane)
    in Pane (created by Styleable(Pane))
    in Styleable(Pane) (created by TabbedPane)
    in TabbedPane (created by Styleable(TabbedPane))
    in Styleable(TabbedPane) (created by DocumentPane)
    in div (created by KeyboardShortcutResponder)
    in KeyboardShortcutResponder (created by GetHookCollectionState)
    in GetHookCollectionState (created by RenderActionCollectionState)
    in RenderActionCollectionState
    in Unknown (created by DocumentPane)
    in DocumentPane
    in Unknown
    in StreamingComponent
    in StreamingComponent (created by Context.Consumer)
    in WithInitialValueWrapper (created by Pane)
    in Pane (created by DeskToolPanes)
    in SplitPaneWrapper (created by DeskToolPanes)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in PanesSplitController (created by DeskToolPanes)
    in div (created by DeskToolPanes)
    in DeskToolPanes (created by DeskTool)
    in div (created by DeskTool)
    in DeskTool (created by withRouter(DeskTool))
    in withRouter(DeskTool) (created by DeskToolPaneStateSyncer)
    in DeskToolPaneStateSyncer (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (created by DefaultLayoutContainer)
    in RouterProvider (created by DefaultLayoutContainer)
    in LoginWrapper (created by DefaultLayoutContainer)
    in DefaultLayoutContainer (created by SanityRoot)
    in SnackbarProvider (created by SanityRoot)
    in div (created by SanityRoot)
    in SanityRoot
    in AppContainer
```

**To Reproduce**

My custom input,

```jsx
import * as React from "react";
import Autocomplete from "part:@sanity/components/autocomplete/default";

export type ContentStringInputProps = {
  type: {
    title: string;
  };
  value: string;
  onChange: () => void;
};

export const ContentStringInput: React.FC<ContentStringInputProps> = (
  props
) => {
  const { type, value } = props;
  const { title } = type;
  return (
    <Autocomplete
        lable={title}
        value={value}
        suggestions={[]}
        onChange={() => console.log("changed")}
      />
  );
};

export default ContentStringInput;
```

My schema,

```js
import ContentStringInput from "../../../components/input/ContentStringInput";

export default {
  name: "pageHeadline",
  type: "document",
  title: "Page Headline",
  fields: [
    {
      name: "id",
      type: "string",
      title: "ID",
    },
    {
      name: "headline",
      type: "string",
      inputComponent: ContentStringInput
    }
  ],
};
```

**Expected behavior**

No errors

**Screenshots**

![image](https://user-images.githubusercontent.com/31038519/87590335-9ab22300-c6b4-11ea-9dd2-1d0693ff9c0b.png)

**Which versions of Sanity are you using?**

@sanity/cli             1.149.16 (latest: 1.149.18)
@sanity/base            1.149.18 (up to date)
@sanity/components      1.149.18 (up to date)
@sanity/core            1.149.18 (up to date)
@sanity/default-layout  1.149.18 (up to date)
@sanity/default-login   1.149.18 (up to date)
@sanity/desk-tool       1.149.18 (up to date)
@sanity/vision          1.149.16 (up to date)

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

6.13.4
v12.16.1

**Comment by vicbergquist** [comment]
Looks like this is something you need help with, so you should ask this in our [Slack community](https://slack.sanity.io) to get the help you need! 👍 We can reopen the issue if this is actually a bug 😊
