### ISSUE TITLE
Unhandled rejection in Node 14

### ISSUE THREAD

**Issue by remisture** [sanity-io/sanity#2123]
**Describe the bug**

Seems like `fsevents` needs to be updated to version 2 in order to work properly in Node 14. 

```
$ npm start

> xxx@1.0.0 start
> sanity start

Using dataset from environment config (production)
✔ Checking configuration files...
⠸ Compiling...webpack built 6872e24822d75110b7a0 in 22601ms
✔ Compiling...
Content Studio successfully compiled! Go to http://localhost:3333
Unhandled rejection: TypeError: fsevents.watch is not a function
    at createFSEventsInstance (/Users/remisture/xxx/node_modules/@sanity/server/node_modules/chokidar/lib/fsevents-handler.js:93:25)
    at setFSEventsListener (/Users/remisture/xxx/node_modules/@sanity/server/node_modules/chokidar/lib/fsevents-handler.js:148:16)
    at FsEventsHandler._watchWithFsEvents (/Users/remisture/xxx/node_modules/@sanity/server/node_modules/chokidar/lib/fsevents-handler.js:351:18)
    at FsEventsHandler.initWatch (/Users/remisture/xxx/node_modules/@sanity/server/node_modules/chokidar/lib/fsevents-handler.js:427:23)
    at FsEventsHandler._addToFsEvents (/Users/remisture/xxx/node_modules/@sanity/server/node_modules/chokidar/lib/fsevents-handler.js:516:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

`npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.`

```
$ npm list fsevents
xxx@1.0.0 /Users/remisture/xxx
└─┬ @sanity/core@2.0.9
  ├─┬ @sanity/server@2.0.9
  │ └─┬ webpack@3.12.0
  │   └─┬ watchpack@1.7.5
  │     └─┬ chokidar@3.4.3
  │       └── fsevents@1.2.13 deduped invalid
  └─┬ chokidar@2.1.8
    └── fsevents@1.2.13
```

**To Reproduce**

```
$ nvm use 14
$ npm start
```

**Expected behavior**

I expect this error not to happen

**Which versions of Sanity are you using?**

```
$ sanity versions
@sanity/cli                 2.0.9 (up to date)
@sanity/base                2.0.9 (up to date)
@sanity/cli                 2.0.9 (up to date)
@sanity/color-input         2.0.9 (up to date)
@sanity/components          2.0.9 (up to date)
@sanity/core                2.0.9 (up to date)
@sanity/dashboard           2.0.9 (up to date)
@sanity/default-layout      2.0.9 (up to date)
@sanity/default-login       2.0.9 (up to date)
@sanity/desk-tool           2.0.9 (up to date)
@sanity/production-preview  2.0.5 (up to date)
@sanity/vision              2.0.9 (up to date)
```

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

```
$ npm -v && node -v
7.0.7
v14.15.0
```

**Comment by rexxars** [comment]
I cannot reproduce, but feel free to reopen if still an issue
