### ISSUE TITLE
[cli] Crash in unattended init mode on insufficient permissions

### ISSUE THREAD

**Issue by rexxars** [sanity-io/sanity#237]
When you try to initialize a new project in unattended mode (`-y`) and specify a project id that either does not exist or is one the current user does  not have access to, the CLI crashes:

```
TypeError: Cannot read property 'displayName' of undefined
    at /node_modules/@sanity/cli/lib/commands/init/initSanity.js:100:15
    at Generator.next (<anonymous>)
    at step (/node_modules/@sanity/cli/lib/commands/init/initSanity.js:61:191)
    at /node_modules/@sanity/cli/lib/commands/init/initSanity.js:61:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

```

**Comment by rexxars** [comment]
Fixed in ee3ab2a
