### ISSUE TITLE
Studio won't start Cannot read property 'problems' of undefined

### ISSUE THREAD

**Issue by vandre** [sanity-io/sanity#2490]
**Describe the bug**

An invalid  document schema with an extra comma in fields  causes Studio to crash

**To Reproduce**

Create a document schema with the following field  (notice the extra-comma between field 3 and field 4

{    name: 'bug',
            type: 'array',
            of: [
              {
                type: 'object',
                fields: [
                   { name:'field1', type: 'string'}
                  ,{ name:'field2', type: 'string'}
                  ,{ name:'field3',  type: 'date', options: { dateFormat: 'M/D/YYYY' } },
                  ,{ name:'field4',  type: 'number'}
                ]
              }
            ]
          }

**Expected behavior**

Studio would open

**Screenshots**

**Which versions of Sanity are you using?**

@sanity/cli             2.5.0 (latest: 2.10.0)
@sanity/base            2.8.0 (latest: 2.10.2)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.8.0 (latest: 2.10.2)
@sanity/default-layout  2.8.0 (latest: 2.10.2)
@sanity/default-login   2.8.0 (up to date)
@sanity/desk-tool       2.8.0 (latest: 2.10.2)
@sanity/vision          2.8.0 (latest: 2.10.0)

**What operating system are you using?** 

Windows 10

**Which versions of Node.js / npm are you running?**
λ npm -v && node -v
6.14.8
v14.11.0

**Additional context**

Stack trace 
```
Uncaught error
Cannot read property 'problems' of undefined

Stack:

TypeError: 
    at http://localhost:3333/static/js/app.bundle.js:212732:95
    at Array.filter (<anonymous>)
    at groupProblems (http://localhost:3333/static/js/app.bundle.js:212732:75)
    at module.exports (http://localhost:3333/static/js/app.bundle.js:208382:47)
    at Object.<anonymous> (http://localhost:3333/static/js/app.bundle.js:3037:43)
    at __webpack_require__ (http://localhost:3333/static/js/vendor.bundle.js:713:30)
    at fn (http://localhost:3333/static/js/vendor.bundle.js:118:20)
    at Object.<anonymous> (http://localhost:3333/static/js/app.bundle.js:219516:38)
    at __webpack_require__ (http://localhost:3333/static/js/vendor.bundle.js:713:30)
    at fn (http://localhost:3333/static/js/vendor.bundle.js:118:20)

(Your browsers Developer Tools may contain more info)

```

**Comment by rexxars** [comment]
This should be fixed in [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization)
