### ISSUE TITLE
CLI exec command does not read manifest from project directory

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#2525]
Running a CLI command from a sub-directory inside a project will correctly find the parent directory where the project is installed, running the command as expected and printing the warning:

```
Not in project directory, assuming context of project at [STUDIO_DIRECTORY]
```

However, `sanity exec` is the only command that seems to look for the manifest in the sub-directory, returning an error instead – in this example from the sub-directory `./scripts`:

```
[STUDIO_DIRECTORY]/node_modules/@sanity/resolver/lib/readManifest.js:40
  throw err;
  ^

Error: ENOENT: no such file or directory, open '[STUDIO_DIRECTORY]/scripts/sanity.json'
    at Object.openSync (node:fs:583:3)
    at Object.readFileSync (node:fs:451:35)
    at readManifestSync ([STUDIO_DIRECTORY]/node_modules/@sanity/resolver/lib/readManifest.js:23:43)
    at readManifest ([STUDIO_DIRECTORY]/node_modules/@sanity/resolver/lib/readManifest.js:63:12)
    at resolveTreeSync ([STUDIO_DIRECTORY]/node_modules/@sanity/resolver/lib/resolver.js:57:44)
    at resolveTree ([STUDIO_DIRECTORY]/node_modules/@sanity/resolver/lib/resolver.js:92:25)
    at resolveParts ([STUDIO_DIRECTORY]/node_modules/@sanity/resolver/lib/resolver.js:49:24)
    at registerLoader ([STUDIO_DIRECTORY]/node_modules/@sanity/plugin-loader/loader.js:35:7)
    at Object.<anonymous> ([STUDIO_DIRECTORY]/node_modules/@sanity/core/lib/actions/exec/pluginLoader.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '[STUDIO_DIRECTORY]/scripts/sanity.json'
}
```

Tested using
@sanity/cli  `2.10.5`
node `v16.1.0`

**Comment by judofyr** [comment]
Thanks for the report! I was able to locate the bug by looking at the code and I have PR ready (https://github.com/sanity-io/sanity/pull/2641), but I haven't actually verified that it fixes the problem since I don't know how to test it.
