### ISSUE TITLE
Strange error in ArrayInput when inside a block component - Improve error messaging

### ISSUE THREAD

**Issue by hypeJunction** [sanity-io/sanity#2704]
**Describe the bug**

```
TypeError: (value || []).some is not a function
    at ArrayInput.render (/static/js/app.bundle.js:499640:44)
    at finishClassComponent (/static/js/vendor.bundle.js:20486:31)
    at updateClassComponent (/static/js/vendor.bundle.js:20436:24)
    at beginWork (/static/js/vendor.bundle.js:21946:16)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:3514:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:3563:16)
    at invokeGuardedCallback (/static/js/vendor.bundle.js:3618:31)
    at beginWork$1 (/static/js/vendor.bundle.js:26529:7)
    at performUnitOfWork (/static/js/vendor.bundle.js:25480:12)
    at workLoopSync (/static/js/vendor.bundle.js:25456:22)
```

**To Reproduce**

```ts
import { CallToAction } from '@fernarzt/cms-types';
import { ObjectField } from '../../../types/createSchema';

export const CallToActionType: ObjectField<CallToAction> = {
  name: 'callToAction',
  type: 'object',
  fields: [
    {
      name: 'text',
      title: 'Text',
      type: 'string',
      validation: (rule) => rule.required(),
    },
    {
      name: 'target',
      title: 'Target',
      type: 'array',
      of: [
        {
          type: 'internalLink',
        },
        {
          type: 'externalLink',
        },
      ],
      validation: (rule) => rule.required().max(1),
    },
  ],
};
```

```ts
import { InternalLink } from '@fernarzt/cms-types';
import { ObjectField } from '../../../types/createSchema';

export const InternalLinkType: ObjectField<InternalLink> = {
  name: 'internalLink',
  title: 'Internal Link',
  type: 'object',
  fields: [
    {
      name: 'ref',
      title: 'Reference',
      type: 'reference',
      to: [
        // @todo: add other types when implemented
        {
          type: 'Hub',
        },
      ],
    },
    {
      name: 'tab',
      title: 'Open In',
      type: 'string',
      options: {
        list: [
          {
            title: 'Same Tab',
            value: '_self',
          },
          {
            title: 'New Tab',
            value: '_blank',
          },
        ],
      },
      defaultValue: '_self',
    },
  ],
};
```

```ts
import { ExternalLink } from '@fernarzt/cms-types';
import { ObjectField } from '../../../types/createSchema';

export const ExternalLinkType: ObjectField<ExternalLink> = {
  name: 'externalLink',
  title: 'External Link',
  type: 'object',
  fields: [
    {
      name: 'href',
      title: 'URL',
      type: 'url',
    },
    {
      name: 'title',
      title: 'Title',
      type: 'string',
    },
    {
      name: 'tab',
      title: 'Open In',
      type: 'string',
      options: {
        list: [
          {
            title: 'Same Tab',
            value: '_self',
          },
          {
            title: 'New Tab',
            value: '_blank',
          },
        ],
      },
      defaultValue: '_self',
    },
  ],
};
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
