### ISSUE TITLE
Content Studio crashes due to invalid hook call

### ISSUE THREAD

**Issue by VictorGlindasPaf** [sanity-io/sanity#2819]
**Describe the bug**

When trying to launch the latest sanity studion, I get an `Invalid hook call` error from the server.

```
Content Studio successfully compiled! Go to http://localhost:3333
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/Users/<me>/Documents/<project>/apps/sanity/node_modules/react/cjs/react.development.js:1476:13)
    at useMemo (/Users/<me>/Documents/<project>/apps/sanity/node_modules/react/cjs/react.development.js:1531:20)
    at Document (/Users/<me>/Documents/<project>/apps/sanity/node_modules/@sanity/base/lib/components/Document.js:49:40)
    at processChild (/Users/<me>/Documents/<project>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/vicgli/Documents/<project>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/<me>/Documents/<project>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/<me>/Documents/<project>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (/Users/<me>/Documents/<project>/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at /Users/<me>/Documents/<project>/apps/sanity/node_modules/@sanity/server/lib/baseServer.js:93:101
```

I have made sure that I only have a single version of React int the project, so that can't be the issue here.

**To Reproduce**

I'm using these versions:
```json
"@sanity/base": "^2.20.0",
"@sanity/core": "^2.20.0",
"@sanity/default-layout": "^2.20.0",
"@sanity/default-login": "^2.19.0",
"@sanity/desk-tool": "^2.20.0",
"@sanity/vision": "^2.20.0",
"sanity-plugin-table": "^2.2.0",
"styled-components": "^5.2.0"
```

1. Install the above versions.
2. Run `yarn sanity start`
3. Open the browser on `http://localhost:3333`

**What operating system are you using?**

macOS Big Sur
11.5.2

**Which versions of Node.js / npm are you running?**

node: 14.16.0
npm: 6.14.11
yarn: 1.22.10

**Comment by stordahl** [comment]
I'm experiencing something similar when attempting to use hooks inside of the Structure Builder

**Comment by spacedawwwg** [comment]
I have just come across the same issue after upgrading to v2.21.0

**Comment by geoffreyjball** [comment]
@VictorGlindasPaf I set up the same environment and couldn't replicate. Could you try running `rm -rf node_modules` and re-installing? If that doesn't work, you could send a zip of your studio to support@sanity.io or by DM to one of us in the Slack community.
