### ISSUE TITLE
New sanity project compiles with errors, studio shows unhandled error.

### ISSUE THREAD

**Issue by chalas-ch** [sanity-io/sanity#2979]
Sanity versions:
```
@sanity/cli             2.22.3 (up to date)
@sanity/base            2.22.3 (up to date)
@sanity/core            2.22.3 (up to date)
@sanity/default-layout  2.22.4 (up to date)
@sanity/default-login   2.22.3 (up to date)
@sanity/desk-tool       2.22.3 (up to date)
@sanity/vision          2.22.3 (up to date)
```

Operating system: `Windows 10 Pro`
```
node.js v16.13.0
npm 8.1.0
```
I started a new sanity project with `sanity init`, installation went without a problem.
When I start the project with `sanity start` I get the following errors.

Browser:
```
Unhandled error
Encountered an unhandled error in this Studio.

TypeError: Object(...) is not a function
    at Object. (/static/js/app.bundle.js:152036:119)
    at __webpack_require__ (/static/js/vendor.bundle.js:713:30)
    at fn (/static/js/vendor.bundle.js:118:20)
    at Object. (/static/js/app.bundle.js:44165:86)
    at __webpack_require__ (/static/js/vendor.bundle.js:713:30)
    at fn (/static/js/vendor.bundle.js:118:20)
    at Object. (/static/js/app.bundle.js:50616:98)
    at __webpack_require__ (/static/js/vendor.bundle.js:713:30)
    at fn (/static/js/vendor.bundle.js:118:20)
    at Object. (/static/js/app.bundle.js:147829:81)
```

Terminal:
```bash
$ sanity start
✔ Checking configuration files...
⠹ Compiling...webpack built 4f1adce1f667030675df in 10994ms
✔ Compiling...
Compiled with warnings.

Warning in ./node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs
158:23-45 "export 'findDimensionValueType' was not found in '../value-types/dimensions.mjs'
 @ ./node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/utils/parse-dom-variant.mjs
 @ ./node_modules/framer-motion/dist/es/render/html/visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/create-visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs
169:23-45 "export 'findDimensionValueType' was not found in '../value-types/dimensions.mjs'
 @ ./node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/utils/parse-dom-variant.mjs
 @ ./node_modules/framer-motion/dist/es/render/html/visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/create-visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs
172:29-51 "export 'findDimensionValueType' was not found in '../value-types/dimensions.mjs'
 @ ./node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/utils/parse-dom-variant.mjs
 @ ./node_modules/framer-motion/dist/es/render/html/visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/create-visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs
177:30-52 "export 'findDimensionValueType' was not found in '../value-types/dimensions.mjs'
 @ ./node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/utils/parse-dom-variant.mjs
 @ ./node_modules/framer-motion/dist/es/render/html/visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/create-visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs
182:21-43 "export 'findDimensionValueType' was not found in '../value-types/dimensions.mjs'
 @ ./node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/utils/parse-dom-variant.mjs
 @ ./node_modules/framer-motion/dist/es/render/html/visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/create-visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/components/Reorder/utils/check-reorder.mjs
19:15-23 "export 'moveItem' was not found in '../../../utils/array.mjs'
 @ ./node_modules/framer-motion/dist/es/components/Reorder/utils/check-reorder.mjs
 @ ./node_modules/framer-motion/dist/es/components/Reorder/Group.mjs
 @ ./node_modules/framer-motion/dist/es/components/Reorder/index.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/gestures/use-focus-gesture.mjs
20:4-15 "export 'useDomEvent' was not found in '../events/use-dom-event.mjs'
 @ ./node_modules/framer-motion/dist/es/gestures/use-focus-gesture.mjs
 @ ./node_modules/framer-motion/dist/es/motion/features/gestures.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/gestures/use-hover-gesture.mjs
20:4-19 "export 'usePointerEvent' was not found in '../events/use-pointer-event.mjs'
 @ ./node_modules/framer-motion/dist/es/gestures/use-hover-gesture.mjs
 @ ./node_modules/framer-motion/dist/es/motion/features/gestures.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/gestures/use-focus-gesture.mjs
21:4-15 "export 'useDomEvent' was not found in '../events/use-dom-event.mjs'
 @ ./node_modules/framer-motion/dist/es/gestures/use-focus-gesture.mjs
 @ ./node_modules/framer-motion/dist/es/motion/features/gestures.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/gestures/use-hover-gesture.mjs
23:4-19 "export 'usePointerEvent' was not found in '../events/use-pointer-event.mjs'
 @ ./node_modules/framer-motion/dist/es/gestures/use-hover-gesture.mjs
 @ ./node_modules/framer-motion/dist/es/motion/features/gestures.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/animation/use-animated-state.mjs
24:21-30 "export 'getOrigin' was not found in '../render/utils/setters.mjs'
 @ ./node_modules/framer-motion/dist/es/animation/use-animated-state.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/projection/node/DocumentProjectionNode.mjs
3:29-49 "export 'createProjectionNode' was not found in './create-projection-node.mjs'
 @ ./node_modules/framer-motion/dist/es/projection/node/DocumentProjectionNode.mjs
 @ ./node_modules/framer-motion/dist/es/projection/node/HTMLProjectionNode.mjs
 @ ./node_modules/framer-motion/dist/es/projection/use-instant-layout-transition.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/gestures/use-pan-gesture.mjs
43:4-19 "export 'usePointerEvent' was not found in '../events/use-pointer-event.mjs'
 @ ./node_modules/framer-motion/dist/es/gestures/use-pan-gesture.mjs
 @ ./node_modules/framer-motion/dist/es/motion/features/drag.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-max.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/animation/animation-controls.mjs
56:16-25 "export 'setValues' was not found in '../render/utils/setters.mjs'
 @ ./node_modules/framer-motion/dist/es/animation/animation-controls.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/gestures/PanSession.mjs
57:16-28 "export 'isMouseEvent' was not found in './utils/event-type.mjs'
 @ ./node_modules/framer-motion/dist/es/gestures/PanSession.mjs
 @ ./node_modules/framer-motion/dist/es/gestures/use-pan-gesture.mjs
 @ ./node_modules/framer-motion/dist/es/motion/features/drag.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-max.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/gestures/use-tap-gesture.mjs
59:4-19 "export 'usePointerEvent' was not found in '../events/use-pointer-event.mjs'
 @ ./node_modules/framer-motion/dist/es/gestures/use-tap-gesture.mjs
 @ ./node_modules/framer-motion/dist/es/motion/features/gestures.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/animation/animation-controls.mjs
61:16-29 "export 'stopAnimation' was not found in '../render/utils/animation.mjs'
 @ ./node_modules/framer-motion/dist/es/animation/animation-controls.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/render/html/visual-element.mjs
77:21-30 "export 'getOrigin' was not found in '../utils/setters.mjs'
 @ ./node_modules/framer-motion/dist/es/render/html/visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/create-visual-element.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/projection/node/HTMLProjectionNode.mjs
7:25-45 "export 'createProjectionNode' was not found in './create-projection-node.mjs'
 @ ./node_modules/framer-motion/dist/es/projection/node/HTMLProjectionNode.mjs
 @ ./node_modules/framer-motion/dist/es/projection/use-instant-layout-transition.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/framer-motion/dist/es/gestures/use-hover-gesture.mjs
9:13-25 "export 'isMouseEvent' was not found in './utils/event-type.mjs'
 @ ./node_modules/framer-motion/dist/es/gestures/use-hover-gesture.mjs
 @ ./node_modules/framer-motion/dist/es/motion/features/gestures.mjs
 @ ./node_modules/framer-motion/dist/es/render/dom/features-animation.mjs
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/toastProvider.js
 @ ./node_modules/@sanity/ui/lib/esm/components/toast/index.js
 @ ./node_modules/@sanity/ui/lib/esm/components/index.js
 @ ./node_modules/@sanity/ui/lib/esm/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Content Studio listening on http://localhost:3333
```

I tried removing `node_modules` and reinstalling with `npm start` several times, deleting and recreating the folder, even deleting the sanity project in the manager and restarting the creation process.
I always end up with the same errors.
I recently updated sanity CLI could it be related ?

Thanks a lot for your help!

**Comment by bjoerge** [comment]
Thanks for letting us know! We have released a fix for this in an upstream dependency. If you remove `node_modules` and reinstall it should now work again.

**Comment by chalas-ch** [comment]
Awesome it works now 👍 thank you for the quick reply 💯 !
