### ISSUE TITLE
sanity cli 2.24.1 upgrade command seems to be failing

### ISSUE THREAD

**Issue by ethancalvo** [sanity-io/sanity#3083]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

running ```sanity upgrade``` using sanity cli 2.24.1 results in ```TypeError: Invalid Version: <missing>```

**To Reproduce**

node v 14.15.4
```sanity upgrade```
returns
```Type Error: Invalid Version: <missing>
    at new f (~/.nvm/versions/node/v14.15.4/lib/node_modules/@sanity/cli/bin/sanity-cli.js:810:4694)
    at d (~/.nvm/versions/node/v14.15.4/lib/node_modules/@sanity/cli/bin/sanity-cli.js:810:8327)
    at Function.m [as gt] (~/.nvm/versions/node/v14.15.4/lib/node_modules/@sanity/cli/bin/sanity-cli.js:810:8364)
    at y (~/.nvm/versions/node/v14.15.4/lib/node_modules/@sanity/cli/bin/sanity-cli.js:5354:3805)
    at Array.filter (<anonymous>)
    at Object.e.default [as action] (~/.nvm/versions/node/v14.15.4/lib/node_modules/@sanity/cli/bin/sanity-cli.js:5354:685)
```
running
```npx @sanity/cli@2.32.2 upgrade```
returns 
```
✖ Resolving dependenciesinking dependencies
✖ An unexpected error occurred: "ENOTDIR: not a directory, lstat '<path to project>/studio/node_modules/react-ace/dist/react-ace.js/main.js'".
✖ Resolving dependenciesinking dependencies

Error: Command failed :(
    at ~/.npm/_npx/.../node_modules/@sanity/cli/bin/sanity-cli.js:3320:2582
    at async Object.e.default [as action] (~/.npm/_npx/.../node_modules/@sanity/cli/bin/sanity-cli.js:5042:2054)
```

**Expected behavior**

Upgrade should result in upgrade with success message and no errors

**Which versions of Sanity are you using?**

2.24.1

**What operating system are you using?**
macOS 12.1

**Which versions of Node.js / npm are you running?**
node 14.15.4
npm 7.20.3

**Additional context**

**Comment by ethancalvo** [comment]
upgrading from 2.24.0 to 2.24.1

**Comment by ethancalvo** [comment]
sorry to keep adding to this. Looks like my yarn.lock file is now gone. I believe prior to this point, yarn was the package manager my project was using. I was using the cli to do the upgrade, not sure if that matters at all. I'd rather use npm so that's cool if yarn is no longer required.

**Comment by rexxars** [comment]
Thanks for reporting! Obscure issue, but #3084 should fix it once released.
Until then, I think you should be able to upgrade by following these steps:

- Delete `node_modules` from the studio folder
- Open `package.json` and set the dependency version of `@sanity/code-input` to `^2.24.2`
- Run `sanity install` (or `npm install`, if you prefer)
