### ISSUE TITLE
Deployment fails with latest patch update

### ISSUE THREAD

**Issue by tubbo** [sanity-io/sanity#3179]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

We just bumped `2.27.1 -> 2.27.2` and came across this issue. Absolutely no idea what's going on.

```
$ sanity deploy
✔ Checking project info

Including the following environment variables as part of the JavaScript bundle:
- SANITY_STUDIO_APP_URL
- SANITY_STUDIO_PREVIEW_SECRET

✔ Clearing output folder (5ms)
✔ Building Sanity (14249ms)
✔ Building index document (47ms)
✔ Minifying JavaScript bundles (23543ms)
✔ Verifying local content
✖ Deploying to Sanity.Studio

o: Internal Server Error - An internal server error occurred
    at onResponse (~/Code/lobby/node_modules/@sanity/cli/bin/sanity-cli.js:4602:536)
    at ~/Code/lobby/node_modules/@sanity/cli/bin/sanity-cli.js:4626:203
    at ~/Code/lobby/node_modules/@sanity/cli/bin/sanity-cli.js:4614:862
    at ~/Code/lobby/node_modules/@sanity/cli/bin/sanity-cli.js:4614:970
    at x (~/Code/lobby/node_modules/@sanity/cli/bin/sanity-cli.js:4650:1029)
    at ~/Code/lobby/node_modules/@sanity/cli/bin/sanity-cli.js:4650:2560
    at s.<anonymous> (~/Code/lobby/node_modules/@sanity/cli/bin/sanity-cli.js:1086:100)
    at T (~/Code/lobby/node_modules/@sanity/cli/bin/sanity-cli.js:1506:6029)
```

**To Reproduce**

1. Have a Sanity studio
2. Update to v2.27.2
3. Try to deploy
4. 💥 

**Expected behavior**

Deployment should have worked, or at least given us a better message than 500 Internal Server Error.

**Screenshots**
n/a

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**

macOS and Ubuntu

**Which versions of Node.js / npm are you running?**

node v14
yarn 1.22.11

**Additional context**

n/a

**Comment by tubbo** [comment]
**update:** We reverted `actions/checkout` from v3 and the problem went away.

**Comment by rexxars** [comment]
Thanks for the update.
