### ISSUE TITLE
can't connect to backend. 

### ISSUE THREAD

**Issue by MaxedAlpha** [sanity-io/sanity#3193]
PS C:\xampp\htdocs\alpha-portfolio\backend_sanity>\backend_sanity> sanity start     
Unhandled rejection: C:\xampp\htdocs\alpha-portfolio\backend_sanity\node_modules\@sanity\core\lib\index.js:10
export const commands = _commands.default;
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)   
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)        
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)    
    at require (node:internal/modules/cjs/helpers:102:18)
    at i (C:\Users\SHADOW\AppData\Roaming\npm\node_modules\@sanity\cli\bin\sanity-cli.js:556:130)
    at e.default (C:\Users\SHADOW\AppData\Roaming\npm\node_modules\@sanity\cli\bin\sanity-cli.js:3608:526)

**Comment by geoffreyjball** [comment]
Haven't been able to replicate this, @MaxedAlpha. What version of the studio and node are you using?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
