### ISSUE TITLE
Dev Preview Fails to Run in PNPM

### ISSUE THREAD

**Issue by dan-made** [sanity-io/sanity#3336]
**Describe the bug**

After selecting pnpm as the package manager for a new installation, running `pnpm run start` results in error which exits with the following error:

```
[...]/node_modules/.pnpm/sanity@3.0.0-dev-preview.8_bl2ogz7y42spdypk3qg5kkb66u/node_modules/sanity/node_modules/.bin/sanity:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/laugharn/github/source/node_modules/.pnpm/sanity@3.0.0-dev-preview.8_bl2ogz7y42spdypk3qg5kkb66u/node_modules/sanity/bin/sanity:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
 ELIFECYCLE  Command failed with exit code 1.
```

**To Reproduce**

1. Create a new Sanity project with `npm create sanity@dev-preview`
2. Choose pnpm as your package manager
4. Run `pnpm run start` 

**Expected behavior**

Sanity should start in dev mode.

**Which versions of Sanity are you using?**

sanity@3.0.0-dev-preview.8

**What operating system are you using?**

MacOS 12.4

**Which versions of Node.js / npm are you running?**

Node 16.15.0
PNPM 7.2.1

**Comment by dan-made** [comment]
Actually, it looks like there is an error before this on step two:

```
Error: Command failed with exit code 1 (EPERM): pnpm install
    at makeError (~/.npm/_npx/681b0a19326c4f58/node_modules/@sanity/cli/bin/sanity-cli.js:20846:17)
    at handlePromise (~/.npm/_npx/681b0a19326c4f58/node_modules/@sanity/cli/bin/sanity-cli.js:21847:33)
    at async installDeclaredPackages (~/.npm/_npx/681b0a19326c4f58/node_modules/@sanity/cli/bin/sanity-cli.js:22052:18)
    at async initSanity (~/.npm/_npx/681b0a19326c4f58/node_modules/@sanity/cli/bin/sanity-cli.js:139952:7)
```

**Comment by evankford** [comment]
@dan-made Found the culprit here, looks like it was trying to run a .bin/sanity file in the wrong place. Solution based on [this article about pnpm](https://dev.to/elpddev/debug-jest-spec-in-vscode-error-missing-after-argument-list-1p3b). 

I also got a pull request made to fix it. For now, you could try using a pnpm patch or edit it directly based on the PR above.

**Comment by rexxars** [comment]
3.0.0-dev-preview.11 is out with a fix for this - let us know if you're still having issues!
