### ISSUE TITLE
Dev Preview Unmet peer dependencies

### ISSUE THREAD

**Issue by bryanjhickey** [sanity-io/sanity#3337]
**Describe the bug**
`npm create sanity@dev-preview` fails with unmet peer dependencies using pnpm.

Errors:
```
dependencies:
+ @sanity/eslint-config-studio 2.0.0
+ eslint 8.17.0
+ prettier 2.7.0
+ react 17.0.2 (18.2.0 is available)
+ react-dom 17.0.2 (18.2.0 is available)
+ react-icons 3.11.0 (4.4.0 is available)
+ sanity 3.0.0-dev-preview.8
+ styled-components 5.3.5

 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
├─┬ @sanity/eslint-config-studio
│ ├─┬ @typescript-eslint/eslint-plugin
│ │ ├── ✕ missing peer typescript@"*"
│ │ └─┬ @typescript-eslint/type-utils
│ │   ├── ✕ missing peer typescript@"*"
│ │   └─┬ @typescript-eslint/utils
│ │     └─┬ @typescript-eslint/typescript-estree
│ │       ├── ✕ missing peer typescript@"*"
│ │       └─┬ tsutils
│ │         └── ✕ missing peer typescript@">=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta"
│ └─┬ @typescript-eslint/parser
│   └── ✕ missing peer typescript@"*"
├─┬ sanity
│ └─┬ @sanity/cli
│   └─┬ esbuild-register
│     └── ✕ missing peer esbuild@">=0.12 <1"
└─┬ styled-components
  └── ✕ missing peer react-is@">= 16.8.0"
Peer dependencies that should be installed:
  esbuild@">=0.12 <1"   react-is@">= 16.8.0"  typescript@>=2.8.0    

hint: If you want peer dependencies to be automatically installed, add "auto-install-peers=true" to an .npmrc file at the root of your project.
hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to an .npmrc file at the root of your project.

Error: Command failed with exit code 1 (EPERM): pnpm install
    at makeError (~/.npm/_npx/681b0a19326c4f58/node_modules/@sanity/cli/bin/sanity-cli.js:20846:17)
    at handlePromise (~/.npm/_npx/681b0a19326c4f58/node_modules/@sanity/cli/bin/sanity-cli.js:21847:33)
    at async installDeclaredPackages (~/.npm/_npx/681b0a19326c4f58/node_modules/@sanity/cli/bin/sanity-cli.js:22052:18)
    at async initSanity (~/.npm/_npx/681b0a19326c4f58/node_modules/@sanity/cli/bin/sanity-cli.js:139952:7)
```

**To Reproduce**
`npm create sanity@dev-preview`

Options selected:

```
✔ Fetching existing projects
? Select project to use sanity-dev-preview [*redacted*]
? Select dataset to use production
? Project output path: /redacted/path/sanity-dev-preview
? Select project template Movie project (schema + sample data)
? Do you want to use TypeScript? Yes
? Add a sampling of sci-fi movies to your dataset on the hosted backend? Yes
✔ Bootstrapping files from template
✔ Resolving latest module versions
✔ Creating default project files
? Package manager to use for installing dependencies? pnpm
```

**Expected behavior**

A studio starter for building with Sanity

**Which versions of Sanity are you using?**
@sanity/cli 2.30.0
Mac OS 11.6.6
NPM 8.5.5
Node 16.14.1

**Comment by malinowskip** [comment]
This seems to be limited to `pnpm`. Adding an `.npmrc` file with `auto-install-peers=true` fixes the installation issue, but Studio still fails to start, with the following error:

```
> v3test@1.0.0 start /Users/pm/Code/v3test
> sanity start

/Users/pm/Code/v3test/node_modules/.pnpm/sanity@3.0.0-dev-preview.9_q7komngtozyr5xrcu6yl2cmxum/node_modules/sanity/node_modules/.bin/sanity:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1040:15)
    at Module._compile (node:internal/modules/cjs/loader:1076:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/pm/Code/v3test/node_modules/.pnpm/sanity@3.0.0-dev-preview.9_q7komngtozyr5xrcu6yl2cmxum/node_modules/sanity/bin/sanity:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)

Node.js v18.4.0
```

**Comment by zvirinz** [comment]
> 
Faced same error. Trick with .npmrc didn't help.

LMDE 5 Elsie
@sanity/cli 2.30.2
npm 8.13.1
pnpm 7.3.0
node 16.14.1

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
