### ISSUE TITLE
Encountered an unhandled error in this Studio.

### ISSUE THREAD

**Issue by safarsafarov** [sanity-io/sanity#3358]
```
 @/static/js/app.bundle.js:17284:3
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:38277:38
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:99887:45
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:98323:38
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:161669:45
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:161635:43
`__webpack_require__@/static/js/vendor.bundle.js:713:30`
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:95333:34
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:15797:67
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:146121:33
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:144377:44
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:71978:36
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:130406:42
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:130385:18
__webpack_require__@/static/js/vendor.bundle.js:713:30
webpackJsonpCallback@/static/js/vendor.bundle.js:26:23
@/static/js/app.bundle.js:1:13
```
```

Package versions:
  @sanity/cli                   2.30.0 (up to date)
  @sanity/base                  2.30.1 (up to date)
  @sanity/core                  2.30.1 (up to date)
  @sanity/default-layout        2.30.1 (up to date)
  @sanity/default-login         2.30.1 (up to date)
  @sanity/desk-tool             2.30.1 (up to date)
  @sanity/eslint-config-studio   2.0.0 (up to date)
  @sanity/vision                2.30.1 (up to date)

```

**Comment by isaksolheim** [comment]
I encountered the same error Firefox. Chrome gives me a more descriptive error message:

```
TypeError: generateHelpUrl is not a function
    at Object. (/static/js/app.bundle.js:160343:204)
    at __webpack_require__ (/static/js/vendor.bundle.js:713:30)
    at fn (/static/js/vendor.bundle.js:118:20)
    at Object. (/static/js/app.bundle.js:160222:16)
    at __webpack_require__ (/static/js/vendor.bundle.js:713:30)
    at fn (/static/js/vendor.bundle.js:118:20)
    at Object. (/static/js/app.bundle.js:156408:17)
    at __webpack_require__ (/static/js/vendor.bundle.js:713:30)
    at fn (/static/js/vendor.bundle.js:118:20)
    at Object. (/static/js/app.bundle.js:156253:38)
```

**Comment by cheng-en-yang** [comment]
Same here, the messages I saw is:
```
@/static/js/app.bundle.js:254344:5
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:17320:38
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:38358:38
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:100515:45
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:98951:38
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:163398:45
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:163364:43
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:95945:34
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:15787:67
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:147865:33
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:146121:44
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:72541:36
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:132104:42
__webpack_require__@/static/js/vendor.bundle.js:713:30
fn@/static/js/vendor.bundle.js:118:20
@/static/js/app.bundle.js:132083:18
__webpack_require__@/static/js/vendor.bundle.js:713:30
webpackJsonpCallback@/static/js/vendor.bundle.js:26:23
@/static/js/app.bundle.js:1:13
```
Can anyone suggest the solution? Thanks!

**Comment by cheng-en-yang** [comment]
> 

okay so I fixed the problem and it was actually a silly mistake I made.
I have ConditionalField in my file and simply forgot to import the module.

**Comment by davidstackio** [comment]
Possible duplicate of #3222. I just did `npm install` after running `sanity upgrade` and it got resolved.

**Comment by RitaDias** [comment]
Hi all!
Thank you so much for helping each other, and sorry for having taken so long to get back to this post!

I will close this now 🙏 
Thanks!
