### ISSUE TITLE
Plugins not found when using pnpm.

### ISSUE THREAD

**Issue by theo0165** [sanity-io/sanity#3417]
**Describe the bug**

When installing dependencies with pnpm sanity can't run because it cant find plugins. Sanity is looking for plugins in the node_modules folder but not in the .pnpm folder that pnpm creates.

When starting the studio with ``sanity start``, the following error is thrown.

```bash
Error: Plugin "@sanity/data-aspects" not found.
Locations tried:
  * /Users/.../src/web/studio/plugins/@sanity/data-aspects
  * /Users/.../src/web/studio/node_modules/@sanity/desk-tool/node_modules/@sanity/data-aspects
  * /Users/.../src/web/studio/node_modules/@sanity/data-aspects
  * /Users/.../src/web/node_modules/@sanity/data-aspects
  * /Users/.../src/node_modules/@sanity/data-aspects
  * /Users/.../node_modules/@sanity/data-aspects
  * /Users/.../node_modules/@sanity/data-aspects
  * /Users/.../node_modules/@sanity/data-aspects
  * /Users/.../node_modules/@sanity/data-aspects
  * /Users/node_modules/@sanity/data-aspects
  * /node_modules/@sanity/data-aspects
Try running "sanity install @sanity/data-aspects"?
    at getPluginNotFoundError (~/.../src/web/studio/node_modules/.pnpm/@sanity+resolver@2.29.5/node_modules/@sanity/resolver/lib/resolvePlugins.js:133:13)
    at ~/.../src/web/studio/node_modules/.pnpm/@sanity+resolver@2.29.5/node_modules/@sanity/resolver/lib/resolvePlugins.js:125:13
    at async Promise.all (index 1)
    at async Promise.all (index 3)
    at async Promise.all (index 3)
```
(Some paths modified for privacy reasons)

**To Reproduce**

1. Create a Sanity project.
2. Install dependencies with pnpm.
3. Try to start the studio with ``sanity start``.

**Expected behavior**

The studio should start like normal and look for plugins in the ``node_modules/.pnpm`` folder.

**Which versions of Sanity are you using?**

```bash
@sanity/cli                   2.30.2 (latest: 3.0.0-dev-preview.11)
@sanity/base                  2.30.1 (up to date)
@sanity/cli                   2.30.2 (latest: 3.0.0-dev-preview.11)
@sanity/core                  2.30.2 (up to date)
@sanity/default-layout        2.30.1 (up to date)
@sanity/default-login         2.30.1 (up to date)
@sanity/desk-tool             2.30.1 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.30.1 (latest: 3.0.0-dev-preview.11)
```

**What operating system are you using?**

``macOS Monterey 12.4``

**Which versions of Node.js / npm are you running?**

```bash
npm: 8.5.0
node: v16.14.2
pnpm: 7.5.0
```

**Additional context**

When tried to install ``@sanity/data-aspects`` with ``sanity install @sanity/data-aspects`` i got the same error with a new plugin. The need to install every plugin like that defeats the purpose of pnpm.

**Comment by theo0165** [comment]
No update on this issue?

**Comment by tomi** [comment]
I managed to get this working by configuring the `node-linker` [configuration option](https://pnpm.io/npmrc#node-linker) to `hoisted` in the `.npmrc` file:

```
node-linker = hoisted
```

**Comment by theo0165** [comment]
@tomi But that kind of defeats the purpose of pnpm, a native solution would be better.

**Comment by rexxars** [comment]
Note that [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) is now released and should fully support pnpm!
