### ISSUE TITLE
_me is not a function - Error message when trying to upload images in Sanity studio V3

### ISSUE THREAD

**Issue by sndrem** [sanity-io/sanity#3451]
**Describe the bug**

I am trying to upload an image in an image-field in the new Sanity Studio version 3. Locally I am able to upload the image, but after running `npx sanity deploy` and navigating to the deployed studio, I get an error when trying to upload images.

I have tried to disable React dev tools, but the bug is still present.

**To Reproduce**

1. Install the preview-version of the Sanity Studio v3
2. Create a schema with an image-field
3. Deploy with `npx sanity deploy`
4. Navigate to your deployed studio
5. Try to create a new document and upload an image.
6. An error will present itself to you. I have seen both `wde is not a function` and `_me` is not a function in two different cases.

**Expected behavior**

I would expect to be able to upload an image as easily as I am able to on localhost.

**Screenshots**
![image](https://user-images.githubusercontent.com/9053627/181475866-e680e42d-4c5a-49c9-bee9-a6783133934b.png)

![image](https://user-images.githubusercontent.com/9053627/181479145-1e14f343-b0f0-45e6-9baf-230f2590f7c3.png)

**Which versions of Sanity are you using?**
```
sanity versions
@sanity/cli                   2.30.0 (latest: 2.30.2)
@sanity/eslint-config-studio   2.0.0 (up to date)
```
```json
 "dependencies": {
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-is": "^17.0.0",
    "sanity": "dev-preview",
    "styled-components": "^5.2.0"
  },
  "devDependencies": {
    "@sanity/eslint-config-studio": "^2.0.0",
    "eslint": "^8.6.0",
    "prettier": "^2.7.1",
    "typescript": "^4.0.0"
  },
```

**What operating system are you using?**
macOS Monterey 12.5

**Which versions of Node.js / npm are you running?**

```
npm -v
8.15.0
```

```
node -v
v17.9.0
```
**Additional context**

```js
react_devtools_backend.js:4026 TypeError: _me is not a function
    at main.0b4f6447.js:4204:34538
    at Array.find (<anonymous>)
    at SG (main.0b4f6447.js:4204:34502)
    at main.0b4f6447.js:4471:12756
    at main.0b4f6447.js:4471:6812
    at Array.map (<anonymous>)
    at K0n.uploadFirstAccepted (main.0b4f6447.js:4471:6787)
    at main.0b4f6447.js:4471:5114
    at main.0b4f6447.js:4395:253
    at Object.QGe (main.0b4f6447.js:81:9374)
    ```

```js
main.d594be1d.js:2202 TypeError: Wde is not a function
    at main.d594be1d.js:4204:34538
    at Array.find (<anonymous>)
    at CU (main.d594be1d.js:4204:34502)
    at main.d594be1d.js:4471:12756
    at main.d594be1d.js:4471:6812
    at Array.map (<anonymous>)
    at Gfn.uploadFirstAccepted (main.d594be1d.js:4471:6787)
    at main.d594be1d.js:4471:5114
    at main.d594be1d.js:4350:262
    at Object.qje (main.d594be1d.js:81:9374)
    ```

**Comment by sndrem** [comment]
This has been resolved in https://github.com/sanity-io/sanity/releases/tag/v3.0.0-dev-preview.12
