### ISSUE TITLE
When using groups a warning is displayed on the browser console

### ISSUE THREAD

**Issue by MauricioRobayo** [sanity-io/sanity#3464]
**Describe the bug**

When using groups the browser console displays the following warning:

> The input component for type "test" has no associated ref element. Please check the implementation of "Unknown" [Object]. If this is a function component, it must be wrapped in React.forwardRef(). Read more at https://docs.sanity.io/help/input-component-no-ref 

I read the info on the link but not sure how to apply what's mention to this particular case.

**To Reproduce**

1. Use the following schema:

```
export default {
  name: "test",
  title: "Test",
  type: "document",
  fields: [
    {
      name: "something",
      title: "Something",
      type: "string",
      group: "group",
    },
  ],
  groups: [
    {
      name: "group",
      title: "Group",
    },
  ],
};
```

2. Start Sanity Studio and go to `http://localhost:3333`, the following warning is shown on the browser's console:

> The input component for type "test" has no associated ref element. Please check the implementation of "Unknown" [Object]. If this is a function component, it must be wrapped in React.forwardRef(). Read more at https://docs.sanity.io/help/input-component-no-ref 

<details>
 <summary>Full warning</summary>

    at FormBuilderInput (eval at ES6ProxyComponentFactory (http://localhost:3333/static/js/app.bundle.js:307769:10), <anonymous>:14:7)
    at ReviewChangesContextProvider (http://localhost:3333/static/js/app.bundle.js:274485:24)
    at FormBuilderContext (eval at ES6ProxyComponentFactory (http://localhost:3333/static/js/app.bundle.js:307769:10), <anonymous>:14:7)
    at SanityFormBuilderContext (http://localhost:3333/static/js/app.bundle.js:116004:18)
    at SanityFormBuilder (eval at ES6ProxyComponentFactory (http://localhost:3333/static/js/app.bundle.js:307769:10), <anonymous>:14:7)
    at form
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at div
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at RegionsWithIntersections (http://localhost:3333/static/js/app.bundle.js:211556:23)
    at StickyOverlay (http://localhost:3333/static/js/app.bundle.js:211143:24)
    at Tracker (http://localhost:3333/static/js/app.bundle.js:208903:23)
    at OverlayEnabled (http://localhost:3333/static/js/app.bundle.js:210965:23)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Container (http://localhost:3333/static/js/app.bundle.js:5025:18)
    at FormView (http://localhost:3333/static/js/app.bundle.js:228808:22)
    at div
    at ScrollContainer (http://localhost:3333/static/js/app.bundle.js:209685:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at BoundaryElementProvider (http://localhost:3333/static/js/app.bundle.js:5221:24)
    at PortalProvider (http://localhost:3333/static/js/app.bundle.js:5607:31)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Fe (http://localhost:3333/static/js/app.bundle.js:9990:17673)
    at ThemeProvider (http://localhost:3333/static/js/app.bundle.js:2783:78)
    at ThemeColorProvider (http://localhost:3333/static/js/app.bundle.js:2858:24)
    at Card (http://localhost:3333/static/js/app.bundle.js:4725:30)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at PaneContent (http://localhost:3333/static/js/app.bundle.js:213825:18)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Flex (http://localhost:3333/static/js/app.bundle.js:4466:21)
    at DocumentPanel (http://localhost:3333/static/js/app.bundle.js:225579:28)
    at div
    at ScrollContainer (http://localhost:3333/static/js/app.bundle.js:209685:25)
    at Tracker (http://localhost:3333/static/js/app.bundle.js:208903:23)
    at EnabledChangeConnectorRoot (http://localhost:3333/static/js/app.bundle.js:209598:23)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Flex (http://localhost:3333/static/js/app.bundle.js:4466:21)
    at DialogProvider (http://localhost:3333/static/js/app.bundle.js:7983:24)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Flex (http://localhost:3333/static/js/app.bundle.js:4466:21)
    at BoundaryElementProvider (http://localhost:3333/static/js/app.bundle.js:5221:24)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Fe (http://localhost:3333/static/js/app.bundle.js:9990:17673)
    at ThemeProvider (http://localhost:3333/static/js/app.bundle.js:2783:78)
    at ThemeColorProvider (http://localhost:3333/static/js/app.bundle.js:2858:24)
    at Card (http://localhost:3333/static/js/app.bundle.js:4725:30)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at LayerProvider (http://localhost:3333/static/js/app.bundle.js:5427:24)
    at LegacyLayerProvider (http://localhost:3333/static/js/app.bundle.js:212329:23)
    at Pane (http://localhost:3333/static/js/app.bundle.js:208534:24)
    at KeyboardShortcutResponder (http://localhost:3333/static/js/app.bundle.js:275178:33)
    at GetHookCollectionState (http://localhost:3333/static/js/app.bundle.js:123457:21)
    at RenderActionCollectionState (http://localhost:3333/static/js/app.bundle.js:275286:23)
    at http://localhost:3333/static/js/app.bundle.js:275224:33
    at InnerDocumentPane (http://localhost:3333/static/js/app.bundle.js:216326:64)
    at ReferenceInputOptionsProvider (http://localhost:3333/static/js/app.bundle.js:83084:24)
    at http://localhost:3333/static/js/app.bundle.js:282282:23
    at DocumentPane (http://localhost:3333/static/js/app.bundle.js:216226:50)
    at PaneRouterProvider (http://localhost:3333/static/js/app.bundle.js:215783:24)
    at DeskToolPane (http://localhost:3333/static/js/app.bundle.js:215666:22)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Fe (http://localhost:3333/static/js/app.bundle.js:9990:17673)
    at ThemeProvider (http://localhost:3333/static/js/app.bundle.js:2783:78)
    at ThemeColorProvider (http://localhost:3333/static/js/app.bundle.js:2858:24)
    at Card (http://localhost:3333/static/js/app.bundle.js:4725:30)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at PaneLayout (http://localhost:3333/static/js/app.bundle.js:214182:24)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at PortalProvider (http://localhost:3333/static/js/app.bundle.js:5607:31)
    at DeskToolProvider (http://localhost:3333/static/js/app.bundle.js:214792:24)
    at http://localhost:3333/static/js/app.bundle.js:207556:27
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://localhost:3333/static/js/app.bundle.js:307769:10), <anonymous>:14:7)
    at DeskToolRoot (http://localhost:3333/static/js/app.bundle.js:205345:52)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://localhost:3333/static/js/app.bundle.js:307769:10), <anonymous>:14:7)
    at RenderTool (http://localhost:3333/static/js/app.bundle.js:296034:30)
    at RouteScope (eval at ES6ProxyComponentFactory (http://localhost:3333/static/js/app.bundle.js:307769:10), <anonymous>:14:7)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Flex (http://localhost:3333/static/js/app.bundle.js:4466:21)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Flex (http://localhost:3333/static/js/app.bundle.js:4466:21)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Flex (http://localhost:3333/static/js/app.bundle.js:4466:21)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at SchemaErrorReporter (eval at ES6ProxyComponentFactory (http://localhost:3333/static/js/app.bundle.js:307769:10), <anonymous>:14:7)
    at DefaultLayout (http://localhost:3333/static/js/app.bundle.js:295660:67)
    at RouterProvider (eval at ES6ProxyComponentFactory (http://localhost:3333/static/js/app.bundle.js:307769:10), <anonymous>:14:7)
    at LoginWrapper (http://localhost:3333/static/js/app.bundle.js:146088:28)
    at NormalizedLoginWrapper
    at DefaultLayoutRoot (http://localhost:3333/static/js/app.bundle.js:144360:39)
    at div
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Box (http://localhost:3333/static/js/app.bundle.js:4294:25)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at Fe (http://localhost:3333/static/js/app.bundle.js:9990:17673)
    at ThemeProvider (http://localhost:3333/static/js/app.bundle.js:2783:78)
    at ThemeColorProvider (http://localhost:3333/static/js/app.bundle.js:2858:24)
    at Card (http://localhost:3333/static/js/app.bundle.js:4725:30)
    at O (http://localhost:3333/static/js/app.bundle.js:9990:20283)
    at SnackbarProvider (eval at ES6ProxyComponentFactory (http://localhost:3333/static/js/app.bundle.js:307769:10), <anonymous>:14:7)
    at ToastProvider (http://localhost:3333/static/js/app.bundle.js:9279:24)
    at LayerProvider (http://localhost:3333/static/js/app.bundle.js:5427:24)
    at PortalProvider (http://localhost:3333/static/js/app.bundle.js:5607:31)
    at UserColorManagerProvider (http://localhost:3333/static/js/app.bundle.js:211328:23)
    at AppProvider (http://localhost:3333/static/js/app.bundle.js:72363:39)
    at Fe (http://localhost:3333/static/js/app.bundle.js:9990:17673)
    at ThemeProvider (http://localhost:3333/static/js/app.bundle.js:2783:78)
    at ZIndexProvider (http://localhost:3333/static/js/app.bundle.js:212371:23)
    at SanityRoot
    at AppContainer (eval at ES6ProxyComponentFactory (http://localhost:3333/static/js/app.bundle.js:307769:10), <anonymous>:14:7)
</details>

Example repository: https://github.com/MauricioRobayo/sanity-groups

**Expected behavior**

No warning to be shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/2121481/182270651-a1302acc-a46c-488a-a8f5-cc8a68b5079c.png)

**Which versions of Sanity are you using?**

```
@sanity/cli                   2.30.2 (up to date)
@sanity/base                  2.30.1 (up to date)
@sanity/core                  2.30.2 (up to date)
@sanity/default-layout        2.30.1 (up to date)
@sanity/default-login         2.30.1 (up to date)
@sanity/desk-tool             2.30.1 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.30.1 (up to date)
```

**What operating system are you using?**

Fedora Linux 36 (Workstation Edition)

**Which versions of Node.js / npm are you running?**

```
npm: 8.13.2
node: v16.15.1
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
