### ISSUE TITLE
I just updated my sanity studio and its giving me this error: generateHelpUrl is not a function

### ISSUE THREAD

**Issue by daniyal-t** [sanity-io/sanity#3509]
I just updated my sanity studio and now I am having this error on the studio.

Unhandled error
Encountered an unhandled error in this Studio.

TypeError: generateHelpUrl is not a function
    at Object. (/static/js/app.bundle.js:161547:204)
    at __webpack_require__ (/static/js/vendor.bundle.js:713:30)
    at fn (/static/js/vendor.bundle.js:118:20)
    at Object. (/static/js/app.bundle.js:161426:16)
    at __webpack_require__ (/static/js/vendor.bundle.js:713:30)
    at fn (/static/js/vendor.bundle.js:118:20)
    at Object. (/static/js/app.bundle.js:157625:17)
    at __webpack_require__ (/static/js/vendor.bundle.js:713:30)
    at fn (/static/js/vendor.bundle.js:118:20)
    at Object. (/static/js/app.bundle.js:157469:38)

These are the modules that were updated 

✔ Modules upgraded:
@sanity/base            2.27.0 → 2.30.4
@sanity/core            2.27.0 → 2.30.3
@sanity/default-layout  2.27.0 → 2.30.4
@sanity/default-login   2.27.0 → 2.30.4
@sanity/desk-tool       2.27.0 → 2.30.4
@sanity/vision          2.27.0 → 2.30.4

**Comment by daniyal-t** [comment]
Installing @sanity/generate-help-url resolved the issue. Thanks
