### ISSUE TITLE
Cannot find module 'styled-components' with Yarn Workspaces

### ISSUE THREAD

**Issue by iduuck** [sanity-io/sanity#3519]
**Describe the bug**

I just tried to add sanity to a mono-repo I am working on. First initialisation was wrong (it says that ID was null, something like this, suppose it has something to do with #1361) – after re-initialising the project, it working. However, I am getting an error when starting the server (`yarn start`/`sanity start`).

```
❯ sanity start
✔ Checking configuration files...

Error: Cannot find module 'styled-components'
Require stack:
- /Users/nick/dev/x/node_modules/@sanity/server/lib/configs/getModulePath.js
- /Users/nick/dev/x/node_modules/@sanity/server/lib/configs/webpack.config.js
- /Users/nick/dev/x/node_modules/@sanity/server/lib/configs/webpack.config.dev.js
- /Users/nick/dev/x/node_modules/@sanity/server/lib/devServer.js
- /Users/nick/dev/x/node_modules/@sanity/server/lib/server.js
- /Users/nick/dev/x/node_modules/@sanity/core/lib/actions/start/startAction.js
- /Users/nick/dev/x/node_modules/@sanity/util/lib/dynamicRequire.js
- /Users/nick/dev/x/node_modules/@sanity/util/lib/lazyRequire.js
- /Users/nick/dev/x/node_modules/@sanity/core/lib/commands/build/buildCommand.js
- /Users/nick/dev/x/node_modules/@sanity/core/lib/commands/index.js
- /Users/nick/dev/x/node_modules/@sanity/core/lib/index.js
- /Users/nick/.asdf/installs/nodejs/16.16.0/.npm/lib/node_modules/@sanity/cli/bin/sanity-cli.js
- /Users/nick/.asdf/installs/nodejs/16.16.0/.npm/lib/node_modules/@sanity/cli/bin/sanity
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getModulePath (~/dev/x/node_modules/@sanity/server/lib/configs/getModulePath.js:15:28)
    at _default (~/dev/x/node_modules/@sanity/server/lib/configs/webpack.config.js:103:63)
    at _default (~/dev/x/node_modules/@sanity/server/lib/configs/webpack.config.dev.js:22:42)
    at getDevServer (~/dev/x/node_modules/@sanity/server/lib/devServer.js:33:68)
    at _default (~/dev/x/node_modules/@sanity/core/lib/actions/start/startAction.js:76:43)
```

**To Reproduce**

1. Create a monorepo
2. Initialize sanity in a subfolder
3. Start firing up the sanity server.

**Expected behavior**

Of course, the server should start.

**Screenshots**

![CleanShot 2022-08-16 at 09 10 18@2x](https://user-images.githubusercontent.com/325241/184819656-7a728c2e-e77c-440f-bb33-2874cf7b9515.png)

**Which versions of Sanity are you using?**

```
❯ sanity versions
@sanity/cli                   2.30.6 (up to date)
@sanity/base                  2.30.5 (up to date)
@sanity/core                  2.30.5 (up to date)
@sanity/default-layout        2.30.5 (up to date)
@sanity/default-login         2.30.5 (up to date)
@sanity/desk-tool             2.30.5 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.30.5 (up to date)
```

**What operating system are you using?** 

macOS 12.3.1

**Which versions of Node.js / npm are you running?**

```
❯ yarn -v && node -v
1.22.19
v16.16.0
```

**Additional context**

N/A

---

EDIT: I double-checked, that `styled-components` was installed and available in `packages/sanity/package.json` and `packages/sanity/node_modules`.

**Comment by DylanMashini** [comment]
Did you end up finding a fix to this?

**Comment by Christian-Garrison** [comment]
@iduuck any fixes you've found?

Slack Conversation Link: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1664850960050879

**Comment by iduuck** [comment]
nope, dismissed cms for now. currently working on other things of the project.

**Comment by Christian-Garrison** [comment]
@iduuck this seems to get me much closer to running the studio.

```
"workspaces": {
  "packages": [
    "packages/*",
    "apps/*"
  ],
  "nohoist": [
    "**/react",
    "**/react/**",
    "**/react-dom",
    "**/react-dom/**",
    "**/styled-components",
    "**/styled-components/**"
  ]
},
```

was researching yarn workspaces and reading up on [nohoist](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/).

However now the issue seems to be resolving this issue in my instance.
```sh
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/Users/cg/Documents/playgrounds/sanity-kitchen-sink/apps/studio/node_modules/react/cjs/react.development.js:1476:13)
    at useMemo (/Users/cg/Documents/playgrounds/sanity-kitchen-sink/apps/studio/node_modules/react/cjs/react.development.js:1531:20)
    at Document (/Users/cg/Documents/playgrounds/sanity-kitchen-sink/apps/studio/node_modules/@sanity/base/lib/components/Document.js:51:40)
    at processChild (/Users/cg/Documents/playgrounds/sanity-kitchen-sink/node_modules/@sanity/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/cg/Documents/playgrounds/sanity-kitchen-sink/node_modules/@sanity/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/cg/Documents/playgrounds/sanity-kitchen-sink/node_modules/@sanity/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/cg/Documents/playgrounds/sanity-kitchen-sink/node_modules/@sanity/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (/Users/cg/Documents/playgrounds/sanity-kitchen-sink/node_modules/@sanity/server/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at /Users/cg/Documents/playgrounds/sanity-kitchen-sink/node_modules/@sanity/server/lib/baseServer.js:95:101
```

**Comment by Christian-Garrison** [comment]
@iduuck This has fixed my issue.

```json
"workspaces": {
  "packages": [
    "packages/*",
    "apps/*"
  ],
  "nohoist": [
    "**/react",
    "**/react/**",
    "**/react-dom",
    "**/react-dom/**",
    "**/@sanity/**"
  ]
},
```

**Comment by jimjeffers** [comment]
@Christian-Garrison Darn - I tried adding `nohoist` and clearing / reinstalling my node_modules but I still end up with the same error as before:

```
yarn run v1.22.19
$ sanity start
✔ Checking configuration files...

Error: Cannot find module 'styled-components'
```

**Comment by vimtor** [comment]
Same issue here using PNPM workspaces

**Comment by madeleineostoja** [comment]
this is also an issue with NPM workspaces, disabling hoisting isn't a solution because that's a yarn specific feature, and I'm not going to migrate my entire ecosystem to Yarn to fix an issue with Sanity. Does sanity not resolve symlinked dependencies? What's the root issue?

**Comment by madeleineostoja** [comment]
I worked around this (in my case it was complaining about `react` and a host of other dependencies missing) by duplicating installs for all sanity dependencies in the root of my workspace, which obviously isn't a longterm solution but at least fixes the immediate issue

**Comment by rexxars** [comment]
Workspaces is going to be a bit of an issue for Sanity v2, but [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) is now released and has much better support for modern tooling like this. We'd love to see people trying it out!

**Comment by madeleineostoja** [comment]
@rexxars I am using Sanity Studio v3

**Comment by iduuck** [comment]
Not a problem anymore for me after creating a new project.
