### ISSUE TITLE
Unable to change api version on studio v3

### ISSUE THREAD

**Issue by eltorio** [sanity-io/sanity#3673]
When using vision it throws an error
```
Error: Existing client instance cannot be reconfigured - use `withConfig(newConfig)` to return a new client
    at SanityClient.config2 [as config] (/Users/***/Development/***/sanity/node_modules/@sanity/client/lib/sanityClient.js:79:13)
    at VisionGui.ensureSelectedApiVersion (/Users/***/Development/**/sanity/node_modules/@sanity/vision/src/components/VisionGui.tsx:430:20)
```
breakpoint at VisionGui.tsx:430
```
wantedApiVersion
'v2021-10-21'
this._client.config().apiVersion
'2021-10-21'
```
It seems that there is a difference beetween studio v3 config (2021-10-21) and vision 3.0.0-dev-preview.17 (v2021-10-21)

**Comment by rexxars** [comment]
Thanks! Fixed in [v3.0.0-dev-preview.20](https://github.com/sanity-io/sanity/releases/tag/v3.0.0-dev-preview.20)
