### ISSUE TITLE
Encountered an unhandled error in this Studio.

### ISSUE THREAD

**Issue by Saifalikhansuri** [sanity-io/sanity#3801]
TypeError: Cannot read properties of null (reading 'jsonType')
    at validateNonObjectFieldsProp (/static/js/app.bundle.js:185298:16)
    at _default (/static/js/app.bundle.js:185266:155)
    at visitors.reduce._objectSpread._problems (/static/js/app.bundle.js:183773:17)
    at Array.reduce ()
    at /static/js/app.bundle.js:183772:21
    at /static/js/app.bundle.js:183791:70
    at /static/js/app.bundle.js:183907:12
    at /static/js/app.bundle.js:183922:95
    at Array.forEach ()
    at traverseSchema (/static/js/app.bundle.js:183921:9)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread.
