### ISSUE TITLE
"Could not completely normalize the editor" error deleting selection with text and link blocks

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [sanity-io/sanity#3854]
**Describe the bug**

Error deleting a text selection that spans a heading and a link.

![image](https://user-images.githubusercontent.com/44397098/200820033-4dde5d7f-31d3-44e0-998d-2b2ef5d7911d.png)

Full trace from local studio:

```
react_devtools_backend.js:4026 Error: 
            Could not completely normalize the editor after 168 iterations! This is usually due to incorrect normalization logic that leaves a node in an invalid state.
          
    at index.es.js:1538:1
    at Object.withoutNormalizing (index.es.js:2173:1)
    at Object.normalize (index.es.js:1509:1)
    at Object.withoutNormalizing (index.es.js:2178:1)
    at Object.delete (index.es.js:5468:1)
    at Object.deleteFragment (index.es.js:165:1)
    at Object.deleteFragment (index.es.js:985:1)
    at HTMLDivElement.<anonymous> (index.es.js:1342:1)
```

**To Reproduce**

1. With a blog starter or similar, create a document that looks like this:

![image](https://user-images.githubusercontent.com/44397098/200819823-bd04ce54-dcdf-4389-9a3a-95b8be76075e.png)

2. Highlight the area shown in the screenshot 
3. Backspace to delete it
4. Observe error

**Expected behavior**

You can delete this selection as for any other.

This is reliably reproducible for for me so please let me know if you have any trouble.

It was originally seen in a much larger document that the editor was deleting chunks while reworking content.

**Screenshots**
See above.

**Which versions of Sanity are you using?**

```
➜  darkgray-seahorse git:(main) ✗ sanity versions
@sanity/cli                   2.35.0 (up to date)
@sanity/base                  2.35.0 (up to date)
@sanity/core                  2.35.0 (up to date)
@sanity/default-layout        2.35.0 (up to date)
@sanity/default-login         2.35.0 (up to date)
@sanity/desk-tool             2.35.1 (up to date)
@sanity/eslint-config-studio   2.0.1 (up to date)
@sanity/vision                2.35.0 (up to date)
```

**What operating system are you using?**

Mac.

**Which versions of Node.js / npm are you running?**

8.19.2
v18.11.0

**Comment by RitaDias** [comment]
Hi!

Thank you for reporting this and sorry for taking so long to answer it.

It looks like this might no longer be a problem in the latest versions of Sanity packages.

Closing the issue with this in mind. However, if you feel that the issue still exists, please re-open / recreate it. 
Once more, thanks :)
