### ISSUE TITLE
sanity login or sanity logout CLI commands in console drive to errors

### ISSUE THREAD

**Issue by JulienDesmettre** [sanity-io/sanity#3925]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**
sanity login or sanity logout CLI commands in console drive to errors : whatever the projects folder , whatever I'm logged in Chrome to https://www.sanity.io/manage or not.
I'm able to start sanity project [localhost/](http://localhost:3333/desk)
sanity commands are available.
sanity deploy or sanity graphql deploy drive to 401 error.

**To Reproduce**
Just go to a sanity project , with sanity CLI installed, ( sanity inited, sanity start works ), try to login / logout / sanity deploy / sanity graphql deploy 

sanity logout returns : `Failed to communicate with the Sanity API:
Unauthorized - Session is expired, please re-authenticate. For more information, see https://docs.sanity.io/help/cli-errors.`

sanity login returns : `⠋ Fetching providers...
o: Unauthorized - Session is expired, please re-authenticate. For more information, see https://docs.sanity.io/help/cli-errors.
    at onResponse (/usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4451:533)
    at /usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4475:279
    at /usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4463:977
    at /usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4463:1085
    at x (/usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4517:1335)
    at /usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4517:2848
    at s.<anonymous> (/usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4525:100)
    at Object.onceWrapper (node:events:509:28)
    at s.emit (node:events:402:35)
    at T (/usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:1793:6030)`

sanity graphql deploy  returns : `Error: Request returned HTTP 401
    at module.exports (~/AAA/_Code/SOIXANTESEIZE/ECOVILLA/ecovilla-website/sanity/node_modules/@sanity/core/lib/util/getUrlHeaders.js:21:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployApiActions (~/AAA/_Code/SOIXANTESEIZE/ECOVILLA/ecovilla-website/sanity/node_modules/@sanity/core/lib/actions/graphql/deployApiAction.js:72:7)` 

**Expected behavior**
No errors

**Screenshots**

**Which versions of Sanity are you using?**
`@sanity/cli                      2.23.0 (latest: 2.35.0)
@sanity/base                     2.35.2 (up to date)
@sanity/client                    3.4.1 (up to date)
@sanity/core                     2.35.0 (up to date)
@sanity/dashboard                2.36.0 (latest: 3.0.0)
@sanity/default-layout           2.35.2 (up to date)
@sanity/default-login            2.35.2 (up to date)
@sanity/desk-tool                2.35.2 (up to date)
@sanity/eslint-config-studio      2.0.1 (up to date)
@sanity/image-url                 1.0.1 (up to date)
@sanity/orderable-document-list   0.1.0 (latest: 1.0.1)
@sanity/vision                   2.35.2 (up to date)`

**What operating system are you using?**
macOs BigSUr Version 11.7.1 (20G918)

**Which versions of Node.js / npm are you running?**
node : v18.0.0
npm : 8.6.0
yarn : 1.22.19 ( using yarn more than npm  ) 

Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional context**
Happens on every Sanity projects / A the the beginning of the week, I was able to command all my deploys on many Sanity projects / I don't remember updating any versions meanwhile / We had a quota exceed on Sanity on 1 project ( but all is managed and reset today ) 

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by JulienDesmettre** [comment]
Hello @bobinska-dev, everything is ok today, but no reasons for this issue has been found.  It's seems to be a very particular case. 2 days after the 1st of November ( reset of bandwidth usage and quotas ) I was able to Login/logout/graphql Deploy by console. I suspected an overage in bandwidth usage caused the issue, but it seems it's not the real reason. I have also a thread in Sanity Slack : https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1669904376685359 . An answer from Peter : "We received a similar of the login issues and it doesn't seem to be tied to usage, although root cause remains unclear."

**Comment by RitaDias** [comment]
Hi @JulienDesmettre 

Thanks for reporting and I am happy to see that it ended up being resolved. Sorry for the extreme delay in replying to the bug!

I will close this for now, If something like this happens in the newer versions of the Sanity package do feel free to open a new bug or reopen this one with the details!

Thanks once more :)
