### ISSUE TITLE
Sanity studio crashes with this error "Error: Unsupported path segment `{}`" while trying to open a document

### ISSUE THREAD

**Issue by DannyPreye** [sanity-io/sanity#4151]
Hello there!

**Describe the bug**
Sanity.io studio crashes whenever i try to open a custom document created from my 'enrollment' schema. 

Here's my schema
```
export default {
    title: "Course Enrollment",
    name: "enrollment",
    type: "document",
    fields: [
        {
            name: "title",
            title: "Title",
            type: "string",
        },
        {
            name: "user",
            type: "reference",
            to: [{ type: "user" }],
            validation: (Rule) => Rule.required(),
        },
        {
            name: "module",
            title: "Module",
            type: "array",
            of: [
                {
                    type: "reference",
                    to: [{ type: "module" }],
                },
            ],
        },
        {
            name: "paymentType",
            title: "Payment Type",
            type: "string",
            options: {
                list: [
                    { title: "Full Course", value: "full" },
                    { title: "Module", value: "module" },
                ],
                layout: "radio",
            },
        },
        {
            name: "course",
            title: "Course",
            type: "reference",
            to: [{ type: "course" }],
        },
        {
            name: "payment_ref",
            title: "Payment Reference",
            type: "string",
            validation: (Rule) => Rule.required(),
        },
    ],
};

```
whenever i try to open a doc i get, it crashes and throws this error

'Error: Unsupported path segment `{}`
    at http://localhost:3333/static/js/app.bundle.js:207040:11
    at Array.reduce (<anonymous>)
    at Object.toString (/static/js/app.bundle.js:207022:15)
    at FormBuilderInputInner (/static/js/app.bundle.js:28738:82)
    at renderWithHooks (/static/js/vendor.bundle.js:17945:18)
    at mountIndeterminateComponent (/static/js/vendor.bundle.js:20624:13)
    at beginWork (/static/js/vendor.bundle.js:21738:16)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:3330:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:3379:16)
    at invokeGuardedCallback (/static/js/vendor.bundle.js:3434:31)
    in StructureError (created by DeskToolRoot)
    in DeskToolRoot (created by RenderTool)
    in ErrorBoundary (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Flex))
    in ForwardRef(Flex) (created by Styled(Component))
    in Styled(Component) (created by SchemaErrorReporter)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Flex))
    in ForwardRef(Flex) (created by Styled(Component))
    in Styled(Component) (created by SchemaErrorReporter)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Flex))
    in ForwardRef(Flex) (created by Styled(Component))
    in Styled(Component) (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by DefaultLayoutRoot)
    in RouterProvider (created by DefaultLayoutRoot)
    in LoginWrapper (created by NormalizedLoginWrapper)
    in NormalizedLoginWrapper (created by DefaultLayoutRoot)
    in DefaultLayoutRoot (created by AppProvider)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Card))
    in Fe (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by ForwardRef(Card))
    in ForwardRef(Card) (created by Styled(Component))
    in Styled(Component) (created by AppProvider)
    in SnackbarProvider (created by AppProvider)
    in ToastProvider (created by AppProvider)
    in LayerProvider (created by AppProvider)
    in PortalProvider (created by AppProvider)
    in UserColorManagerProvider (created by AppProvider)
    in AppProvider (created by SanityRoot)
    in Fe (created by ThemeProvider)
    in ThemeProvider (created by SanityRoot)
    in ZIndexProvider (created by SanityRoot)
    in SanityRoot
    in AppContainer'

**Expected behavior**

I want to be able to see the data that has been added to each enrollment doc and modify it.

**Screenshots**
here's a live screenshot of the error
![digitec_backend-–-Sanity](https://user-images.githubusercontent.com/99923947/216050359-3de5b947-4897-49ec-ba4f-8934a200dde5.png)

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.2.5 (latest: 3.2.6)

**What operating system are you using?**
Linux Ubuntu

**Which versions of Node.js / npm are you running?**
v17.8.0

**Comment by justshiv** [comment]
Hi @DannyPreye! Thank you for reaching out to us. I'm sorry it took us so long to get back to you. It looks like this should no longer be a problem in the latest versions of Sanity packages, so I'll be closing this issue. 

If you're still having trouble with the latest version of Sanity packages please feel free to re-open this and get back in touch. 🙂
