### ISSUE TITLE
Document suddenly reverts to old version while editing portable text

### ISSUE THREAD

**Issue by vildeserina** [sanity-io/sanity#4164]
**Describe the bug**

While editing content inside a portable text editor, the document suddenly reverts to an old version without warning. 

Hard to say what triggers it exactly, but it seems like it's happening more often when editing list items.  

See recording and other info here here: https://teamkult.notion.site/Issue-with-portable-text-e39d1135a3e9472089dfb2efbfd5fe2f

**To Reproduce**

1. Edit content and list-items inside a portable text editor
2. Document suddenly reverts without warning to old version

**Expected behavior**

Stay on the same draft and only update after pressing "publish"

**Screenshots**

Example 1: https://file.notion.so/f/s/2eceb51d-ccdb-4152-8906-1653532f26b8/Sanity_bug.mov?id=405fa361-4ed4-4e8f-a059-94ee594f77f3&table=block&spaceId=cfb25968-f3e7-4842-9ff4-4183203cc436&expirationTimestamp=1675872384492&signature=AfT5Dm9HRuv3MW8IJ3uQM_PKBFdQGu9AKFH1NNpa4tM&downloadName=Sanity_bug.mov

Example 2: https://file.notion.so/f/s/ec248bb8-d1d0-4dad-9854-442819064d39/happened_again.mov?id=5ef2ede2-98b5-46f5-bb32-cc37fc139496&table=block&spaceId=cfb25968-f3e7-4842-9ff4-4183203cc436&expirationTimestamp=1675871304903&signature=DANx5bWx2dlpNm1JgiuS-A969sl6WbrkeirvpxXBFkA

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

```
❯ sanity versions
@sanity/cli (global)             3.2.5 (latest: 3.2.6)
@sanity/asset-utils              1.3.0 (up to date)
@sanity/dashboard                3.1.3 (up to date)
@sanity/image-url                1.0.2 (up to date)
@sanity/orderable-document-list  1.0.2 (up to date)
@sanity/studio-secrets           2.0.2 (up to date)
@sanity/ui                       1.2.2 (up to date)
@sanity/vision                   3.2.6 (up to date)
sanity                           3.2.6 (up to date)
```

**What operating system are you using?**
macOS Monterey 12.4

**Which versions of Node.js / npm are you running?**

`8.1.2
v16.13.2`

**Additional context**

I've added some examples of the schema from the document here: https://teamkult.notion.site/Issue-with-portable-text-e39d1135a3e9472089dfb2efbfd5fe2f

**Comment by vildeserina** [comment]
Was able to reproduce when making lots of fast changes to the document, seems like the saving process isn't able to keep up. 

Got two error messages:
 
![Screenshot 2023-02-08 at 20 32 52](https://user-images.githubusercontent.com/53511085/217635509-9cf9dcf5-5b2e-468f-ae27-78ea6b052304.jpg)

![Screenshot 2023-02-08 at 20 36 27](https://user-images.githubusercontent.com/53511085/217635497-4bd5177f-5e48-4a01-ae4f-b9a57cdcc840.jpg)

**Comment by mckelveygreg** [comment]
This has been happening to us since v2! I thought it would get better after our migration, but still, unannounced and misappropriated reverts that history has a hard time keeping track of. In fact, it will assign the diffs to people who were merely looking at the article. 

I'm glad someone was able to find some good repro and errors, we haven't had that much luck. This is very spooky... 👻

**Comment by vildeserina** [comment]
### Update: Still Experiencing Document Reversion and Data Corruption Issues - Likely Related to Rapid Input and Concurrent Editing

I'm still encountering the document reversion and data corruption issues within the Portable Text editor, although it does appear to be slightly less frequent than initially reported.  For the last two years, I've spent COUNTLESS of hours trying to solve this issue of get to the bottom of it in several ways, and I've always made sure to update to the latest versions of Sanity in these last two years. 


**Crucially, the problem is significantly exacerbated when the Sanity Studio is open in multiple browser tabs.** This strongly suggests a concurrency issue I think, where simultaneous editing sessions are interfering with each other.

My colleagues have also reported experiencing similar document corruption, and we've identified **copy-pasting large amounts of text into the Portable Text editor as a potential trigger.**  However, for me personally, the common denominator appears to be **rapid changes and input within the Portable Text field.**  It seems that when edits are made quickly, the system struggles to maintain data integrity, leading to these errors.

To illustrate the issue, here's a recent example (from january 14th) of what occurs:

**What happened:**

1.  I am working on writing text in a portable text field.
2.  Suddenly, strange things happen. The text I'm working on duplicates itself and ends up in multiple places.
3. History of the document not record this, or, sometimes it will record me deleting text, other times not, it's very inconsistent:

   **To be more precise, the text I am actively writing or have recently written within the Portable Text field becomes duplicated and interspersed with existing content in a seemingly random and illogical manner.  This results in garbled and nonsensical text, requiring manual correction and often leading to document reversion.**




Here's an image of the result: 
 
![Image](https://github.com/user-attachments/assets/b7887de0-03fd-4a58-91a9-d2e0d5417912)

Sometimes the whole field will disappear behind this error-message afterwards: 
"Non-unique keys
Several items in this list share the same identifier (key). Every item must have an unique
identifier.
• Developer info
Generate unique keys"

![Image](https://github.com/user-attachments/assets/61aa202b-e9e4-4a75-8a37-b44aaf091e21)

Here's a loom showcasing an example of this happening: https://www.loom.com/share/4c8f0f3342414a819431b5528d5fdf2b?sid=de2efee5-9575-4dbf-9da9-0fd11c0c0176

Also, here's another loom, showcasing how the revision history disappears: https://www.loom.com/share/ff0ad0d28a9a497b87598cc6065b7f84?sid=53b7ecb7-7ee2-4317-9552-838e0042762f

(Although this exact issue might have been resolved). 

**Error messages received in the console while this happens:**

`hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)
overrideMethod @ hook.js:608
hook.js:608 Error rendering diff component: 
overrideMethod @ hook.js:608
2hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)
overrideMethod @ hook.js:608
hook.js:608 Error rendering diff component: 
overrideMethod @ hook.js:608
2hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)
overrideMethod @ hook.js:608
hook.js:608 Error rendering diff component: 
overrideMethod @ hook.js:608
2hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)
overrideMethod @ hook.js:608
hook.js:608 Error rendering diff component: 
overrideMethod @ hook.js:608
2hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)
overrideMethod @ hook.js:608
hook.js:608 Error rendering diff component: 
overrideMethod @ hook.js:608
2hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)
overrideMethod @ hook.js:608
hook.js:608 Error rendering diff component: 
overrideMethod @ hook.js:608
2hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)
overrideMethod @ hook.js:608
hook.js:608 Error rendering diff component: 
overrideMethod @ hook.js:608
hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to update. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to remove. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to update. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to remove. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to update. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to remove. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to update. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to remove. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to update. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to remove. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to update. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to remove. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": "(Om dere vil kan dere gjerne også sende oss innspill på dette, om dere allerede har god oversikt over hvilke mål som det er viktigst å fokusere på i 2025)"
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to update. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Multiple spans have `_key` 0376488f7267. It's ambiguous which one to remove. {
  "_key": "555fa9e1fc5d",
  "_type": "block",
  "children": [
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    },
    {
      "_key": "0376488f7267",
      "_type": "span",
      "marks": [],
      "text": ""
    }
  ],
  "markDefs": [],
  "style": "normal"
}
overrideMethod @ hook.js:608
hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)
overrideMethod @ hook.js:608
hook.js:608 Error rendering diff component: 
overrideMethod @ hook.js:608
2hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)
overrideMethod @ hook.js:608
hook.js:608 Error rendering diff component: 
overrideMethod @ hook.js:608
hook.js:608 Error: No such schema type: figure
    at 322a0034-c048508b1c6b580f.js:1769:44786
    at 322a0034-c048508b1c6b580f.js:1769:44830
    at 322a0034-c048508b1c6b580f.js:1:9278
    at 3015-3f8b66efdd0b6659.js:1:3223316
    at u._next (5546-17354e8cc625939a.js:1:35966)
    at push.76607.e.next (5546-17354e8cc625939a.js:1:28660)
    at t._subscribe (5546-17354e8cc625939a.js:1:34468)
    at push.24001.t._trySubscribe (5546-17354e8cc625939a.js:1:27342)
    at 5546-17354e8cc625939a.js:1:27265
    at o (5546-17354e8cc625939a.js:1:41120)`


However, I seem to also experience several variations of this bug. 

For example, I can click on "publish" on a document, and all the content inside the fields of of the document will be wiped out, like in this clip, which I recorded in june: https://www.loom.com/share/83c226801ed4491ea9ba54dee29f97fe?sid=67381c71-d8d3-4e12-a7af-3dde69f7d490 (ironically, this problem happend on a blog post bragging about Sanitys amazingness 🥲)

It seems like it will happen more often when editing documents with huge amounts of text (which is ... typical for me), but I've also experienced this issue with taxonomy-documents which only contain a single title-string-field. 

1. I will create a new document
2. Type in the title of the document
3. Click on publish
4. The title field is wiped out
5. Sometimes, if I just wait, the issue resolves itself
6. Sometimes, the content in the title field is truly gone and I need to type it all out again and click on publish. 

Again, it seems like if I type to fast, this happens. 


I feel like I'm going crazy trying to resolve this, hope I can get some help! I keep updating to the next version of sanity, hoping it will be resolved.

**Comment by bjoerge** [comment]
Hi @vildeserina, thanks so much for the detailed report, and sorry it took us so long to follow up.

This looks very similar to the issues we addressed with https://github.com/sanity-io/sanity/pull/11198, released in [v5.14.0](https://github.com/sanity-io/sanity/releases/tag/v5.14.0).

Have you been experiencing this in v5.14.0 or newer?
