### ISSUE TITLE
No "sanity.json" file found in plugin "@sanity/vision

### ISSUE THREAD

**Issue by krishnaUIDev** [sanity-io/sanity#4172]
Can someone please help me with the below error. Sanity.json file already in the root level.

```
krishnasanity:sanity: Error: No "sanity.json" file found in plugin "@sanity/vision"
krishnasanity:sanity: See https://docs.sanity.io/help/missing-plugin-sanity-json       
krishnasanity:sanity:     at handleManifestReadError (G:/enji.dev/node_modules/.pnpm/@sanity+resolver@2.35.3/node_modules/@sanity/resolver/lib/readManifest.js:27:11)
krishnasanity:sanity:     at G:/enji.dev/node_modules/.pnpm/@sanity+resolver@2.35.3/node_modules/@sanity/resolver/lib/readManifest.js:56:60
```

Sanity.json file

```
{
  "root": true,
  "project": {
    "name": ""
  },
  "api": {
    "projectId": "",
    "dataset": ""
  },
  "plugins": [
    "@sanity/base",
    "@sanity/default-layout",
    "@sanity/default-login",
    "@sanity/desk-tool"
  ],
  "env": {
    "development": {
      "plugins": [
        "@sanity/vision"
      ]
    }
  },
  "parts": [
    {
      "name": "part:@sanity/base/schema",
      "path": "./schemas/schema"
    }
  ]
}
```
Package json versions.

```
    "@sanity/base": "^2.35.5",
    "@sanity/core": "^2.35.6",
    "@sanity/default-layout": "^2.35.5",
    "@sanity/default-login": "^2.35.5",
    "@sanity/desk-tool": "^2.35.5",
    "@sanity/eslint-config-studio": "^2.0.1",
    "@sanity/vision": "^3.3.1",
```

Sanity cli version 2.27.0

**Comment by thobas-dnvgl** [comment]
You should use @sanity/vision 2.x if the rest of the dependencies (including sanity studio) is 2.x
