### ISSUE TITLE
The desk tool crash in V3 when exploring history of a document if an edit was made by a user that has been removed

### ISSUE THREAD

**Issue by thobas-dnvgl** [sanity-io/sanity#4176]
**Describe the bug**

Our V3 studio crashed when opening the dropdown with "Current version" with some documents. It's hard to know why, I only have guesses but the exact same steps do not crash in studio V2.

This is the crash:
![2023-02-14_14-42-11](https://user-images.githubusercontent.com/66472571/218759701-b98a98fc-3be0-482d-9562-4ec7446773cc.png)

The pixelated part is:
```
ES: Forbidden - Not allowed to fetch user with ID pM8V33Tqo
    at onResponse (https://XXX/static/desk-257f76bb-3a1ef6c8.js:18:14817)
    at https://XXX/static/desk-257f76bb-3a1ef6c8.js:2:452
    at p (https://XXX/static/desk-257f76bb-3a1ef6c8.js:3:3295)
    at https://XXX/static/desk-257f76bb-3a1ef6c8.js:3:3136
    at S (https://XXX/static/desk-257f76bb-3a1ef6c8.js:3:2552)
    at s.<computed> (https://XXX/static/desk-257f76bb-3a1ef6c8.js:3:1129)
```

Notice the 403 in the browser console. I checked and we don't have a user with the ID `pM8V33Tqo` so my guess is that the history panel is fetching information about users who have edited this document but one of them does not exist anymore so we get a … 403?!

**To Reproduce**

Pretty sure that you can reproduce it like this:
1. Have at least 2 users
2. Edit a document
3. Delete the user who edited the document
4. Open the history of the document with the other user:

![2023-02-14_14-42-40](https://user-images.githubusercontent.com/66472571/218762944-2819515d-48f4-4366-90bf-5054e89e1c92.png)

**Expected behavior**

No crash like in V2 (same document, same network error with 403 displayed in the console, but not desk crash):
![2023-02-14_14-42-30](https://user-images.githubusercontent.com/66472571/218762841-045ed1f0-1ace-435c-81c1-a45327f7cd1e.png)

**Screenshots**

**Which versions of Sanity are you using?**

```
@sanity/cli (global)  3.3.1 (up to date)
@sanity/color-input   3.0.2 (up to date)
@sanity/icons         2.2.2 (up to date)
@sanity/table         1.0.1 (up to date)
@sanity/ui            1.2.2 (up to date)
@sanity/util          3.3.1 (up to date)
@sanity/uuid          3.0.1 (up to date)
@sanity/vision        3.3.1 (up to date)
sanity                3.3.1 (up to date)
```

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

```
9.4.2
v16.19.0
```

**Additional context**

**Comment by jordanl17** [comment]
Hi @thobas-dnvgl - We have since releases sanity@4 and sanity@5. Are you able to clarify whether this is still an issue for you?

**Comment by thobas-dnvgl** [comment]
Hi. As the test scenario is a bit involved (deleted user in the history), let's close it. Will reopen if I encounter that case again.
