### ISSUE TITLE
Cannot get the start point in the node at path [13] because it has no start text node.

### ISSUE THREAD

**Issue by ritesh-kanchi** [sanity-io/sanity#4181]
**Describe the bug**
While editing Portable Text field in Sanity, after a certain amount of writing, the Desk Tool crashes, displaying the following error:

```
Error: Cannot get the start point in the node at path [13] because it has no start text node.
Error: Cannot get the start point in the node at path [13] because it has no start text node.
    at Object.point (https://STUDIOLINK/static/desk-2d9c1d72-f6119bba.js:1458:1149)
    at Object.start (https://STUDIOLINK/static/desk-2d9c1d72-f6119bba.js:1458:3600)
    at Object.range (https://STUDIOLINK/static/desk-2d9c1d72-f6119bba.js:1458:3152)
    at $$ (https://STUDIOLINK/static/desk-2d9c1d72-f6119bba.js:1460:5104)
    at m5t (https://STUDIOLINK/static/desk-2d9c1d72-f6119bba.js:1461:1112)
    at h7 (https://STUDIOLINK/static/desk-2d9c1d72-f6119bba.js:87:19575)
    at _0e (https://STUDIOLINK/static/desk-2d9c1d72-f6119bba.js:89:44188)
    at w0e (https://STUDIOLINK/static/desk-2d9c1d72-f6119bba.js:89:39891)
    at U$e (https://STUDIOLINK/static/desk-2d9c1d72-f6119bba.js:89:39814)
    at $x (https://STUDIOLINK/static/desk-2d9c1d72-f6119bba.js:89:39664)
```

**To Reproduce**
Not sure, happened after updating Sanity to 3.4.0.

**Expected behavior**

The desk tool shouldn't crash in the process of editing a Portable Text/Block Content Field

**Which versions of Sanity are you using?**
@sanity/cli (global)          3.4.0 (up to date)
@sanity/eslint-config-studio  2.0.1 (up to date)
@sanity/vision                3.4.0 (up to date)
sanity                        3.4.0 (up to date)

**What operating system are you using?**
MacOS

**Which versions of Node.js / npm are you running?**
npm 9.1.1
Node.js v18.12.1

**Comment by ritesh-kanchi** [comment]
Just working with Portable Text - in general it feels a lot more buggy in Sanity v3 than it ever did on v2 - not sure of what majorly changed behind the scenes? But I'll get errors like this, along with general publishing errors. I'll write a chunk of text, hit Publish, and then half of it disappears, along with the Version History for it. 

Another example that recreates this problem as specified above is writing, switching to bold while writing, and switching back out. It creates either a weird duplication of text effect or mass-deletion, before throwing this Desk Tool error.

**Comment by kmelve** [comment]
Thanks for reporting @ritesh-kanchi! We're looking into this, stay tuned!

**Comment by skogsmaskin** [comment]
We are working on this. Unfortunately `v.3.4.0` introduced some regressions 😓 

> Another example that recreates this problem as specified above is writing, switching to bold while writing, and switching back out. It creates either a weird duplication of text effect or mass-deletion, before throwing this Desk Tool error.

This issue should be fixed now with the release of `3.5.1`.

**Comment by SG60** [comment]
v3.6 seems to have resolved this for me

**Comment by justshiv** [comment]
Hi @ritesh-kanchi! Thank you for reaching out to us. It looks like this was resolved and should no longer be a problem in the latest versions of Sanity packages, so I'll be closing this issue.

If you're still having trouble with the latest version of Sanity packages please feel free to re-open this and get back in touch. 🙂
