### ISSUE TITLE
Desk-tool crashes on special characters in inspection search

### ISSUE THREAD

**Issue by danielmartinsen** [sanity-io/sanity#4189]
**Describe the bug**
Desk-tool crashes if you try to search with special characters in some cases, and gives an error message that the text is an invalid regex expression.

**To Reproduce**
1. Go to a document with some data
2. Open inspect
4. Try to search for /Date(
6. See error

**Full error-message**
`Error: Invalid regular expression: /(k/: Unterminated group`

`SyntaxError: Invalid regular expression: /(k/: Unterminated group
    at new RegExp (<anonymous>)
    at ReactClassComponent.render (webpack-internal:///./node_modules/@rexxars/react-json-inspector/json-inspector.js:82:33)
    at finishClassComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19747:31)
    at updateClassComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19693:24)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21606:16)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27421:14)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26552:12)
    at workLoopSync (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26461:5)
    at renderRootSync (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26429:7)
    at recoverFromConcurrentError (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25845:20)
    at performConcurrentWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25745:22)
    at workLoop (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:266:34)
    at flushWork (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:533:21)
`

**Which versions of Sanity are you using?**
- @sanity/cli (global), v3.2.6
- @sanity/vision, v3.3.1
- sanity, v3.3.1

**What operating system are you using?**
- Windows 11 Pro, version 22H2

**Which versions of Node.js / npm are you running?**
- Node.js, v9.4.1
- NPM, v18.14.0

**Comment by pedrobonamin** [comment]
Hi!
Thank you for reporting this and sorry for taking so long to answer it.
It looks like this might no longer be a problem in the latest versions of Sanity packages.

Closing the issue with this in mind.
However, if you feel that the issue still exists, please re-open / recreate it.

Once more, thanks 😄
