### ISSUE TITLE
Studio crashes when following Getting Started guide

### ISSUE THREAD

**Issue by seenickcode** [sanity-io/sanity#4212]
**To Reproduce**

1. Go to the [guide](https://www.sanity.io/docs/create-a-sanity-project)
2. Follow steps to create project there.
3. Attempt to start via `npm run dev`
4. A stack trace appears on the CLI

```
npm run dev

> sanity-project@1.0.0 dev /Users/seenickcode/code/fcc-v2/cms2
> sanity dev

✔ Checking configuration files...
Sanity Studio using vite@4.1.4 ready in 849ms and running at http://localhost:3333/
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
10:42:41 AM [vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'config')
  Plugin: vite:css
  File: /Users/seenickcode/code/fcc-v2/cms2/.sanity/runtime/index.html?html-proxy&direct&index=1.css:undefined:undefined
      at getTailwindConfig (/Users/seenickcode/code/fcc-v2/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:81:62)
      at /Users/seenickcode/code/fcc-v2/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:124:92
      at /Users/seenickcode/code/fcc-v2/node_modules/tailwindcss/lib/processTailwindFeatures.js:43:11
      at plugins (/Users/seenickcode/code/fcc-v2/node_modules/tailwindcss/lib/index.js:20:104)
      at LazyResult.runOnRoot (/Users/seenickcode/code/fcc-v2/cms2/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:339:16)
      at LazyResult.runAsync (/Users/seenickcode/code/fcc-v2/cms2/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:393:26)
      at LazyResult.async (/Users/seenickcode/code/fcc-v2/cms2/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:221:30)
      at LazyResult.then (/Users/seenickcode/code/fcc-v2/cms2/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:206:17)
```

5. An error appears at the URL provided by the CLI `localhost:3333`

```
[plugin:vite:css] [postcss] Cannot read properties of undefined (reading 'config')
    at getTailwindConfig (/Users/seenickcode/code/fcc-v2/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:81:62)
    at /Users/seenickcode/code/fcc-v2/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:124:92
    at /Users/seenickcode/code/fcc-v2/node_modules/tailwindcss/lib/processTailwindFeatures.js:43:11
    at plugins (/Users/seenickcode/code/fcc-v2/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/Users/seenickcode/code/fcc-v2/cms2/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/Users/seenickcode/code/fcc-v2/cms2/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/Users/seenickcode/code/fcc-v2/cms2/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/Users/seenickcode/code/fcc-v2/cms2/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/lazy-result.js:206:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
```

**Expected behavior**

Studio should start up.

**Screenshots**

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

```
sanity versions
@sanity/cli                   2.25.0 (latest: 3.5.0)
@sanity/eslint-config-studio   2.0.1 (up to date)
@sanity/vision                 3.5.0 (up to date)
```

**What operating system are you using?**

macOS

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

```
npm -v && node -v
8.18.0
v18.8.0
```

**Additional context**

A SO solution [here](https://stackoverflow.com/questions/73040459/sanity-error-cannot-read-properties-of-undefined-reading-config) seems to fix the issue. 

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by rexxars** [comment]
This is a bug/feature of Vite, where it finds a PostCSS/tailwind configuration in a parent folder of where your Sanity installation is. See https://github.com/sanity-io/sanity/issues/3884#issuecomment-1353828118 for a workaround.
