### ISSUE TITLE
Sanity provided template out of the box will not deploy to GraphQL

### ISSUE THREAD

**Issue by codingChewie** [sanity-io/sanity#4228]
**Describe the bug**

After running the command:

```
yarn deploy-graphql
```

Throws error in the terminal:

```
Error: Encountered anonymous inline object "callToAction" for field/type "ModuleImage". To use this field with GraphQL you will need to create a top-level schema type for it. See https://docs.sanity.io/help/schema-lift-anonymous-object-type
    at createLiftTypeError (~/dir/sanity-studio/node_modules/sanity/lib/_chunks/deployApiAction-6b41a7ab.js:561:10)
    at getObjectDefinition (~/dir/sanity-studio/node_modules/sanity/lib/_chunks/deployApiAction-6b41a7ab.js:262:13)
    at _convertType (~/dir/sanity-studio/node_modules/sanity/lib/_chunks/deployApiAction-6b41a7ab.js:228:14)
    at convertType (~/dir/sanity-studio/node_modules/sanity/lib/_chunks/deployApiAction-6b41a7ab.js:240:20)
    at ~/dir/sanity-studio/node_modules/sanity/lib/_chunks/deployApiAction-6b41a7ab.js:287:95
    at Array.map (<anonymous>)
    at getObjectDefinition (~/dir/sanity-studio/node_modules/sanity/lib/_chunks/deployApiAction-6b41a7ab.js:287:28)
    at _convertType (~/dir/sanity-studio/node_modules/sanity/lib/_chunks/deployApiAction-6b41a7ab.js:231:14)
    at convertType (~/dir/sanity-studio/node_modules/sanity/lib/_chunks/deployApiAction-6b41a7ab.js:240:20)
    at ~/dir/sanity-studio/node_modules/sanity/lib/_chunks/deployApiAction-6b41a7ab.js:412:47
```

- created backend directory in my project: `mkdir sanity-test`
- new install: `npm create sanity@latest`
- fetched existing project:`foo-bar [243ndw4]`
- chose an existing dataset: `production`
- validated path: `/dir/project/sanity-test`
- select project template: [`E-commerce (Shopify)`](https://github.com/sanity-io/sanity-shopify-studio)
- Do you want TypeScript: `Yes`
- Package manager to use for installing dependencies? `Yarn`
- checking if it works: `yarn dev` I can use the backend, test data from Shopify renders correctly

**Expected behavior**

To deploy the dataset to GraphQL so I can render it on the frontend.

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.5.0 (up to date)
@sanity/asset-utils           1.3.0 (up to date)
@sanity/color-input           3.0.2 (up to date)
@sanity/eslint-config-studio  2.0.1 (up to date)
@sanity/vision                3.5.0 (up to date)
sanity                        3.5.0 (up to date)
```

**What operating system are you using?**

macOS Monterey Version 12.6

**Which versions of Node.js / npm are you running?**

- NPM: 8.19.2
- Node: v18.12.1

**Comment by codingChewie** [comment]
Figured out how to resolve this error and refactored in this [working commit ](https://github.com/sanity-io/sanity-shopify-studio/commit/c37eed78622370fda92b5b3a222e2d77c4154638). Now running the error of:

> Encountered anonymous inline object "spot" for field/type "productHotspots"

after the `yarn deploy-graphql` command

**Comment by bjoerge** [comment]
Thanks for reporting @codingChewie 

Closing due to inactivity/lack of signal, assuming its been fixed by now. Let us know if this is still an issue.
