### ISSUE TITLE
RollupError: "tap" is not exported by "node_modules/rxjs/_esm5/index.js", imported by "node_modules/@sanity/portable-text-editor/lib/index.esm.js".

### ISSUE THREAD

**Issue by dev-searchengineunity** [sanity-io/sanity#4511]
**Describe the bug**
Unable to run sanity deploy after updating to sanity v3.11.1.

**To Reproduce**

1. Update sanity to v.3.11.1
2. `sanity deploy` the studio
3. See error
```
✖ Build Sanity Studio

RollupError: "tap" is not exported by "node_modules/rxjs/_esm5/index.js", imported by "node_modules/@sanity/portable-text-editor/lib/index.esm.js".
    at error (file://~/SEU/Site%20Builder/siteBuilderV2/packages/studio/node_modules/rollup/dist/es/shared/rollup.js:2091:30)
    at Module.error (file://~/SEU/Site%20Builder/siteBuilderV2/packages/studio/node_modules/rollup/dist/es/shared/rollup.js:13133:16)
    at Module.traceVariable (file://~/SEU/Site%20Builder/siteBuilderV2/packages/studio/node_modules/rollup/dist/es/shared/rollup.js:13515:29)
    at ModuleScope.findVariable (file://~/SEU/Site%20Builder/siteBuilderV2/packages/studio/node_modules/rollup/dist/es/shared/rollup.js:11997:39)
    at FunctionScope.findVariable (file://~/SEU/Site%20Builder/siteBuilderV2/packages/studio/node_modules/rollup/dist/es/shared/rollup.js:6820:38)
    at ChildScope.findVariable (file://~/SEU/Site%20Builder/siteBuilderV2/packages/studio/node_modules/rollup/dist/es/shared/rollup.js:6820:38)
    at ReturnValueScope.findVariable (file://~/SEU/Site%20Builder/siteBuilderV2/packages/studio/node_modules/rollup/dist/es/shared/rollup.js:6820:38)
    at ReturnValueScope.findVariable (file://~/SEU/Site%20Builder/siteBuilderV2/packages/studio/node_modules/rollup/dist/es/shared/rollup.js:6820:38)
    at ChildScope.findVariable (file://~/SEU/Site%20Builder/siteBuilderV2/packages/studio/node_modules/rollup/dist/es/shared/rollup.js:6820:38)
    at Identifier.bind (file://~/SEU/Site%20Builder/siteBuilderV2/packages/studio/node_modules/rollup/dist/es/shared/rollup.js:7914:40)
```

**Expected behavior**
Sanity studio to be successfully built.

**Which versions of Sanity are you using?**
@sanity/cli (global)          3.11.1 (up to date)
@sanity/color-input            3.1.0 (up to date)
@sanity/dashboard              3.1.4 (up to date)
@sanity/eslint-config-studio   2.0.1 (up to date)
@sanity/vision                3.11.1 (up to date)
sanity                        3.11.1 (up to date)

**What operating system are you using?**
macOS Ventura 13.3.1

**Which versions of Node.js / npm are you running?**
node v18.13.0
npm v8.19.3

**Additional context**
Sanity can successfully deploy when rolled back to sanity v3.10.3.

**Comment by dev-searchengineunity** [comment]
Unable to reproduce said issue a second time.
