### ISSUE TITLE
GraphQL deploy error: Failed to load configuration file "..sanity.config.ts": matchMedia not present, legacy browsers require a polyfill

### ISSUE THREAD

**Issue by shubhamdhingra007** [sanity-io/sanity#4602]
**Describe the bug**

We are migrating from Sanity v2 to v3 and when this has started happening. Everything is successfully migrated, the project runs locally, on the hosted environment, and also builds successfully.
However, when we are trying to deploy GraphQL APIs, we get the below error:
```
Error: Failed to load configuration file "/Users/shubhamdhingra/Desktop/Workspace/vds/authoring/vds-studio/sanity.config.ts":
matchMedia not present, legacy browsers require a polyfill
    at getStudioConfig (~/Desktop/Workspace/vds/authoring/vds-studio/node_modules/sanity/lib/_internal/cli/threads/getGraphQLAPIs.js:49:13)
    at resolveGraphQLApis (~/Desktop/Workspace/vds/authoring/vds-studio/node_modules/sanity/lib/_internal/cli/threads/getGraphQLAPIs.js:90:28)
    at getGraphQLAPIsForked (~/Desktop/Workspace/vds/authoring/vds-studio/node_modules/sanity/lib/_internal/cli/threads/getGraphQLAPIs.js:77:26)
    at Object.<anonymous> (~/Desktop/Workspace/vds/authoring/vds-studio/node_modules/sanity/lib/_internal/cli/threads/getGraphQLAPIs.js:70:1)
```

**To Reproduce**

1. Go to the project root
2. Execute `npm run deploy:graphql`

**Expected behavior**

Graphql schema deploys to the studio without error

**Screenshots**

_Error:_
<img width="1255" alt="Screenshot 2023-06-18 at 9 02 22 AM" src="https://github.com/sanity-io/sanity/assets/29521597/e1820e70-58bf-4664-9a8d-ae69ca5e2bd6">

_Failing Sanity code:_ (Added logs in the Sanity's bundle)
<img width="1325" alt="Screenshot 2023-06-18 at 8 33 17 AM" src="https://github.com/sanity-io/sanity/assets/29521597/4d21d936-e0e0-4882-ae02-f2b085328ee9">

_sanity.cli.ts_
<img width="661" alt="Screenshot 2023-06-18 at 9 09 47 AM" src="https://github.com/sanity-io/sanity/assets/29521597/a707bc82-392d-46e2-88d2-89d17e0c6f0c">

_Scripts:_
<img width="836" alt="Screenshot 2023-06-18 at 9 01 29 AM" src="https://github.com/sanity-io/sanity/assets/29521597/76847fc6-0c5b-4c43-82b1-654f11207600">

**Which versions of Sanity are you using?**
<img width="625" alt="Screenshot 2023-06-18 at 9 06 09 AM" src="https://github.com/sanity-io/sanity/assets/29521597/264d57b3-8f11-449c-831b-bf715c409edf">

**What operating system are you using?**
MacOS Ventura 13.4 (22F66)

**Which versions of Node.js / npm are you running?**
npm: 9.5.1
node: 18.16.0

**Additional context**
1. apiVersion using '2021-06-07'

**Comment by shubhamdhingra007** [comment]
A little more to add.
I observed this when we are importing from a 3rd party library. 
In context, this 3rd party library is our ui-components library and works completely fine with all the famous frameworks(Gatsby, Next, CRA based) and bundlers(webpack, Vite, etc.)

**Comment by ashleyryan** [comment]
Some more details - the issue is coming from a dependency of one of our dependencies, react-slick. This error is most commonly seen in Jest because jsdom doesn't implement matchMedia. 

I was trying to figure out why this isn't a problem in Vite in other apps when the library is imported in Node, and the issue seems to be that in the context this graphql job runs, `window` is defined, so the code thinks it's a browser context. Why is window defined here?

**Comment by bjoerge** [comment]
Thanks for reporting, and apologies for the silence. Years have passed since this issue was opened, and there hasn't been any recent activity, so assuming this has been fixed by now. Please open a new issue if not.

**Comment by shubhamdhingra007** [comment]
Forgot to update. This was fixed when we updated Sanity to v4 last year.
