### ISSUE TITLE
`v3.15.0` won't start the studio

### ISSUE THREAD

**Issue by pascalwengerter** [sanity-io/sanity#4808]
**Describe the bug**

I've just updated our dependencies across the board, but when I bump `sanity` to `v3.15.0` it crashes with the following:

```sh
$ sanity dev
TypeError: require$$2.agent is not a function
    at Object.<anonymous> (/Users/pascal/Projects/brain/polarstern-cms/node_modules/@sanity/cli/lib/_chunks/loadEnv-ccf0665e.js:1159:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/pascal/Projects/brain/polarstern-cms/node_modules/@sanity/cli/lib/_chunks/cli-6f8d21d5.js:1:1054)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
```

**To Reproduce**

Install `sanity` to `v3.15.0` and run `{npm run,yarn} dev`.

**Which versions of Sanity are you using?**

```sh
@sanity/cli (global)          3.15.0 (up to date)
@sanity/color                  2.2.5 (up to date)
@sanity/eslint-config-studio   3.0.0 (up to date)
@sanity/icons                  2.4.1 (up to date)
@sanity/table                  1.0.1 (up to date)
@sanity/types                 3.15.0 (up to date)
@sanity/vision                3.15.0 (up to date)
sanity                        3.14.0 (latest: 3.15.0)
```

**What operating system are you using?**

macOS

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v && yarn -v` in the terminal and copy-paste the result here.

```sh
8.19.3
v18.13.0
1.22.19
```

**Comment by indeox** [comment]
Yup, confirmed. Getting it here as well

```sh
> sanity versions
require$$2.agent is not a function
@sanity/cli (global)          3.15.0 (up to date)
@sanity/cli                   3.15.0 (up to date)
@sanity/code-input             4.1.1 (up to date)
@sanity/eslint-config-studio   3.0.0 (up to date)
@sanity/icons                  2.4.1 (up to date)
@sanity/image-url              1.0.2 (up to date)
@sanity/scheduled-publishing   1.2.0 (up to date)
@sanity/table                  1.0.1 (up to date)
@sanity/types                 3.15.0 (up to date)
@sanity/ui                     1.7.4 (up to date)
@sanity/vision                3.15.0 (up to date)
sanity                        3.15.0 (up to date)

> sanity dev
TypeError: require$$2.agent is not a function
    at Object.<anonymous> (~/.../node_modules/@sanity/cli/lib/_chunks/loadEnv-ccf0665e.js:1159:12)
    at Object.<anonymous> (~/.../node_modules/@sanity/cli/lib/index.js:6:15)

> sanity build
TypeError: require$$2.agent is not a function
    at Object.<anonymous> (~/.../node_modules/@sanity/cli/lib/_chunks/loadEnv-ccf0665e.js:1159:12)
    at Object.<anonymous> (~/.../node_modules/@sanity/cli/lib/index.js:6:15)
```

**Comment by sharpsteelsoftware** [comment]
same here

**Comment by stipsan** [comment]
What version of `get-it` do you have in your `node_modules`?
```bash
yarn why get-it
```
And paste here if you can 🙌

**Comment by indeox** [comment]
@stipsan This is mine if it helps

```sh
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "get-it"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "get-it@8.1.3"
info Has been hoisted to "get-it"
info Reasons this module exists
   - Hoisted from "sanity#get-it"
   - Hoisted from "@sanity#cli#get-it"
   - Hoisted from "sanity#@sanity#export#get-it"
   - Hoisted from "sanity#@sanity#import#get-it"
   - Hoisted from "@sanity#scheduled-publishing#@sanity#util#@sanity#types#@sanity#client#get-it"
   - Hoisted from "next-sanity#@sanity#preview-kit#@sanity#groq-store#@sanity#types#@sanity#client#get-it"
info Disk size without dependencies: "720KB"
info Disk size with unique dependencies: "1.01MB"
info Disk size with transitive dependencies: "1.61MB"
info Number of shared dependencies: 22
=> Found "@sanity/client#get-it@8.4.1"
info This module exists because "@sanity#client" depends on it.
info Disk size without dependencies: "836KB"
info Disk size with unique dependencies: "1.13MB"
info Disk size with transitive dependencies: "1.72MB"
info Number of shared dependencies: 22
=> Found "@sanity/types#get-it@8.4.2"
info Reasons this module exists
   - "@sanity#types#@sanity#client" depends on it
   - Hoisted from "@sanity#types#@sanity#client#get-it"
info Disk size without dependencies: "836KB"
info Disk size with unique dependencies: "1.13MB"
info Disk size with transitive dependencies: "1.72MB"
info Number of shared dependencies: 22
=> Found "sanity#@sanity/client#get-it@8.4.2"
info This module exists because "sanity#@sanity#client" depends on it.
info Disk size without dependencies: "836KB"
info Disk size with unique dependencies: "1.13MB"
info Disk size with transitive dependencies: "1.72MB"
info Number of shared dependencies: 22
```

**Comment by stipsan** [comment]
Ah I see, I think I know what happened here, `@sanity/client` needs a new enough version of `get-it` that has:
```
import {agent} from 'get-it/middleware'
```
But somehow the `package-lock.json` or `yarn.lock` haven't updated everything. Hang on

**Comment by stipsan** [comment]
Ok a fix is on the way. In the meantime could you try deleting your `package-lock.json` or `yarn.lock`, and your `node_modules` and then do a reinstall? That should pull in the right versions and let you run `sanity dev`

**Comment by indeox** [comment]
@stipsan Yep! Now that you've explained it, it makes sense. And the workaround works 👍 

Alternatively in yarn, this works too until the fix is out.
```json
  "resolutions": {
    "get-it": "^8.4.2"
  }
```
