### ISSUE TITLE
projectId not being found

### ISSUE THREAD

**Issue by jcdiprose** [sanity-io/sanity#4995]
sanity.cli.js is configured with projectId under api.projectId but running deploy logs error `Error: sanity.cli.js does not contain a project identifier ("api.projectId"),`

Versions.. 
@sanity/cli (global)          3.18.0 (up to date)
@sanity/dashboard              3.1.5 (up to date)
@sanity/eslint-config-studio   3.0.1 (up to date)
@sanity/vision                3.18.0 (up to date)
sanity                        3.18.0 (up to date)

Full error message
```
Error: sanity.cli.js does not contain a project identifier ("api.projectId"), which is required for the Sanity CLI to communicate with the Sanity API
    at ~/Documents/_projects/home-detox/sanity/node_modules/@sanity/cli/lib/_chunks/cli-5477dc77.js:13342:2311
    at Object.deployStudio [as default] (~/Documents/_projects/home-detox/sanity/node_modules/sanity/lib/_chunks/deployAction-1bf04727.js:50:18)
    at Object.action (~/Documents/_projects/home-detox/sanity/node_modules/sanity/lib/_chunks/_internal-43314de3.js:126:23)
```

**Comment by NavidGoalpure** [comment]
I have this error too, when running "sanity import ...". "sanity dev" works finely:
`import { deskTool } from 'sanity/desk';
import { visionTool } from '@sanity/vision';
import { defineConfig } from 'sanity';
import schemas from './schemas/schema';
import { I18nFields } from 'sanity-plugin-i18n-fields';
export default defineConfig({
  name: 'default',
  title: 'foo',
  projectId: 'bar',
  dataset: 'prelive',
  plugins: [
    deskTool(),
    visionTool(),
    I18nFields({
      locales: [
        { code: 'en', label: '🇬🇧', title: 'English', default: true },
        { code: 'fa', label: '🇮🇷', title: 'Iran' },
      ],
    }),
  ],
  schema: {
    types: schemas,
  },
});
`
my package.json:
`{
    ...
    "start": "sanity start",
    "build": "sanity build",
    "dev": "sanity dev",
    "dataset": "sanity dataset"
  },
  "keywords": [
    "sanity"
  ],
  "dependencies": {
    "@sanity/cli": "^3.18.1",
    "@sanity/vision": "^3.18.1",
    "eslint": "^8.6.0",
    "prop-types": "^15.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.6.0",
    "sanity": "^3.18.1",
    "sanity-plugin-i18n-fields": "^1.0.0",
    "styled-components": "^5.2.0"
  }
}
`

**Comment by vucenovic** [comment]
I am running into the same problem running `sanity deploy`. My `sanity.cli.js` looks like this:

```
import {defineCliConfig} from 'sanity/cli'

export default defineCliConfig({
  api: {
    projectId: '<projectID>',
    dataset: 'production'
  }
})
```

**Comment by jcdiprose** [comment]
I actually never got around this. Eventually I built the static files and hosted on netlify as a seperate app so I could deliver to the client... Not a reasonable solution but a solution none the less

**Comment by vucenovic** [comment]
Which OS did you run it in? Running the deploy command from Windows actually doesn't make any difference for me I believe, so it is an easy workaround for now.

**Comment by bjoerge** [comment]
Closing due to inactivity. Please reopen and provide a minimal repro if still an issue in recent versions.
