### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by benlrichards** [sanity-io/sanity#5087]
**Describe the bug**

When I run 'sanity deploy' for the first time on a fresh project, I get an error on Build Sanity Studio:
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at userAgentContains (~/dev/your-project/node_modules/framer-motion/dist/cjs/index.js:4223:25)
    at Object.<anonymous> (~/dev/your-project/node_modules/framer-motion/dist/cjs/index.js:4229:20)
    at extensions..js (~/dev/your-project/node_modules/esbuild-register/dist/node.js:4838:24)
    at Object.newLoader (~/dev/your-project/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (~/dev/your-project/node_modules/esbuild-register/dist/node.js:4838:24)

**To Reproduce**

1. Create new project via 'npm create sanity@latest'
1. cd into project folder
2. Run 'sanity deploy'
3. See error

**Expected behavior**

Successful deployment of my project on Sanity hosting

**Which versions of Sanity are you using?**

@sanity/cli (global)          3.18.1 (up to date)
@sanity/eslint-config-studio   3.0.1 (up to date)
@sanity/vision                3.18.1 (up to date)
sanity                        3.18.1 (up to date)

**What operating system are you using?**

Mac OS 14

**Which versions of Node.js / npm are you running?**

10.2.0
v21.0.0

**Comment by bcromijn** [comment]
I'm experiencing the same just now

**Comment by bndkt** [comment]
Node 21 seems to be the problem here, it works with Node 20.

**Comment by geball** [comment]
Can you please try node `v21.1.0`?

**Comment by rexxars** [comment]
If you are having this issue, please use Node 18, 20 or a version higher than v21.1.0.
