### ISSUE TITLE
@sanity/vision is not working with bun

### ISSUE THREAD

**Issue by flayks** [sanity-io/sanity#5234]
**Describe the bug**

It seems impossible to run `@sanity/vision` using Bun. It throws an error when accessing the Studio.

```
✘ [ERROR] Failed to resolve entry for package "sanity". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
    at resolvePackageEntry (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
    at tryNodeResolve (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at Context.resolveId (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
    at Object.resolveId (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44276:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65922:21
    at async file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:39976:34
    at async requestCallbacks.on-resolve (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:1373:22)
    at async handleRequest (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:729:13)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:39956:19)
    at handlePlugins (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:786:5)
    at /Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:2186:27)
    at Object.context (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:46041:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    ../../node_modules/@sanity/vision/lib/index.esm.js:2:29:
      2 │ import { definePlugin } from 'sanity';
        ╵                              ~~~~~~~~

✘ [ERROR] Could not resolve "sanity/router"

    ../../node_modules/@sanity/vision/lib/index.esm.js:3:22:
      3 │ import { route } from 'sanity/router';
        ╵                       ~~~~~~~~~~~~~~~

  You can mark the path "sanity/router" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Failed to resolve entry for package "sanity". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
    at resolvePackageEntry (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
    at tryNodeResolve (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at Context.resolveId (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
    at Object.resolveId (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44276:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65922:21
    at async file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:39976:34
    at async requestCallbacks.on-resolve (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:1373:22)
    at async handleRequest (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:729:13)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:39956:19)
    at handlePlugins (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:786:5)
    at /Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:2186:27)
    at Object.context (/Users/flayks/sites/sanity-test/node_modules/vite/node_modules/esbuild/lib/main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///Users/flayks/sites/sanity-test/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:46041:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    ../../node_modules/@sanity/vision/lib/_chunks/SanityVision-oM6_d46E.js:2:26:
      2 │ import { useClient } from 'sanity';
        ╵                           ~~~~~~~~
```

**To Reproduce**

`bun i @sanity/vision`

**Expected behavior**

It should work properly

**Which versions of Sanity are you using?**

3.20.0

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

10.2.3
v20.9.0

**Comment by bjoerge** [comment]
@flayks is this still an issue for you?

**Comment by flayks** [comment]
> @flayks is this still an issue for you?

Yes, the issue is still happening with `@sanity/vision` using Bun (v1.0.17).

**Comment by bjoerge** [comment]
What version of sanity?

**Comment by flayks** [comment]
The very latest one I'm afraid 🙈

**Comment by flayks** [comment]
Of course, here is a minimal reproduction repo: https://github.com/flayks/sanity-turborepo-bun

I'm using Turborepo but I don't see why it would cause any problem. Just run `bun dev` at the root and you should have this error:
```
> bun dev                                                                 
$ turbo run dev --parallel
• Packages in scope: sanity
• Running dev in 1 packages
• Remote caching disabled
sanity:dev: cache bypass, force executing a538cfeae85bf40c
sanity:dev: $ sanity dev
sanity:dev: ✔ Checking configuration files...
sanity:dev: Sanity Studio using vite@4.5.1 ready in 430ms and running at http://localhost:3333/
sanity:dev: ✘ [ERROR] Failed to resolve entry for package "sanity". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]
sanity:dev: 
sanity:dev:     ../../node_modules/vite/node_modules/esbuild/lib/main.js:1373:21:
sanity:dev:       1373 │         let result = await callback({
sanity:dev:            ╵                      ^
sanity:dev: 
sanity:dev:     at packageEntryFailure (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28725:11)
sanity:dev:     at resolvePackageEntry (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28722:5)
sanity:dev:     at tryNodeResolve (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28453:20)
sanity:dev:     at Context.resolveId (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28212:28)
sanity:dev:     at Object.resolveId (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44276:64)
sanity:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sanity:dev:     at async file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:65929:21
sanity:dev:     at async file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:39976:34
sanity:dev:     at async requestCallbacks.on-resolve (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:1373:22)
sanity:dev:     at async handleRequest (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:729:13)
sanity:dev: 
sanity:dev:   This error came from the "onResolve" callback registered here:
sanity:dev: 
sanity:dev:     ../../node_modules/vite/node_modules/esbuild/lib/main.js:1292:20:
sanity:dev:       1292 │       let promise = setup({
sanity:dev:            ╵                     ^
sanity:dev: 
sanity:dev:     at setup (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:39956:19)
sanity:dev:     at handlePlugins (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:1292:21)
sanity:dev:     at buildOrContextImpl (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:978:5)
sanity:dev:     at Object.buildOrContext (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:786:5)
sanity:dev:     at /Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:2186:68
sanity:dev:     at new Promise (<anonymous>)
sanity:dev:     at Object.context (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:2186:27)
sanity:dev:     at Object.context (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:2026:58)
sanity:dev:     at prepareEsbuildOptimizerRun (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:46041:35)
sanity:dev: 
sanity:dev:   The plugin "vite:dep-pre-bundle" was triggered by this import
sanity:dev: 
sanity:dev:     ../../node_modules/@sanity/vision/lib/_chunks/index-ShIdQoSo.js:2:57:
sanity:dev:       2 │ import { defineLocaleResourceBundle, definePlugin } from 'sanity';
sanity:dev:         ╵                                                          ~~~~~~~~
sanity:dev: 
sanity:dev: ✘ [ERROR] Could not resolve "sanity/router"
sanity:dev: 
sanity:dev:     ../../node_modules/@sanity/vision/lib/_chunks/index-ShIdQoSo.js:3:22:
sanity:dev:       3 │ import { route } from 'sanity/router';
sanity:dev:         ╵                       ~~~~~~~~~~~~~~~
sanity:dev: 
sanity:dev:   You can mark the path "sanity/router" as external to exclude it from the bundle, which will remove this error.
sanity:dev: 
sanity:dev: ✘ [ERROR] Failed to resolve entry for package "sanity". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]
sanity:dev: 
sanity:dev:     ../../node_modules/vite/node_modules/esbuild/lib/main.js:1373:21:
sanity:dev:       1373 │         let result = await callback({
sanity:dev:            ╵                      ^
sanity:dev: 
sanity:dev:     at packageEntryFailure (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28725:11)
sanity:dev:     at resolvePackageEntry (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28722:5)
sanity:dev:     at tryNodeResolve (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28453:20)
sanity:dev:     at Context.resolveId (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28212:28)
sanity:dev:     at Object.resolveId (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44276:64)
sanity:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sanity:dev:     at async file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:65929:21
sanity:dev:     at async file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:39976:34
sanity:dev:     at async requestCallbacks.on-resolve (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:1373:22)
sanity:dev:     at async handleRequest (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:729:13)
sanity:dev: 
sanity:dev:   This error came from the "onResolve" callback registered here:
sanity:dev: 
sanity:dev:     ../../node_modules/vite/node_modules/esbuild/lib/main.js:1292:20:
sanity:dev:       1292 │       let promise = setup({
sanity:dev:            ╵                     ^
sanity:dev: 
sanity:dev:     at setup (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:39956:19)
sanity:dev:     at handlePlugins (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:1292:21)
sanity:dev:     at buildOrContextImpl (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:978:5)
sanity:dev:     at Object.buildOrContext (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:786:5)
sanity:dev:     at /Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:2186:68
sanity:dev:     at new Promise (<anonymous>)
sanity:dev:     at Object.context (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:2186:27)
sanity:dev:     at Object.context (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:2026:58)
sanity:dev:     at prepareEsbuildOptimizerRun (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:46041:35)
sanity:dev: 
sanity:dev:   The plugin "vite:dep-pre-bundle" was triggered by this import
sanity:dev: 
sanity:dev:     ../../node_modules/@sanity/vision/lib/_chunks/resources-bPLLJ09x.js:1:39:
sanity:dev:       1 │ import { defineLocalesResources } from 'sanity';
sanity:dev:         ╵                                        ~~~~~~~~
sanity:dev: 
sanity:dev: ✘ [ERROR] Failed to resolve entry for package "sanity". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]
sanity:dev: 
sanity:dev:     ../../node_modules/vite/node_modules/esbuild/lib/main.js:1373:21:
sanity:dev:       1373 │         let result = await callback({
sanity:dev:            ╵                      ^
sanity:dev: 
sanity:dev:     at packageEntryFailure (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28725:11)
sanity:dev:     at resolvePackageEntry (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28722:5)
sanity:dev:     at tryNodeResolve (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28453:20)
sanity:dev:     at Context.resolveId (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28212:28)
sanity:dev:     at Object.resolveId (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44276:64)
sanity:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sanity:dev:     at async file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:65929:21
sanity:dev:     at async file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:39976:34
sanity:dev:     at async requestCallbacks.on-resolve (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:1373:22)
sanity:dev:     at async handleRequest (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:729:13)
sanity:dev: 
sanity:dev:   This error came from the "onResolve" callback registered here:
sanity:dev: 
sanity:dev:     ../../node_modules/vite/node_modules/esbuild/lib/main.js:1292:20:
sanity:dev:       1292 │       let promise = setup({
sanity:dev:            ╵                     ^
sanity:dev: 
sanity:dev:     at setup (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:39956:19)
sanity:dev:     at handlePlugins (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:1292:21)
sanity:dev:     at buildOrContextImpl (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:978:5)
sanity:dev:     at Object.buildOrContext (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:786:5)
sanity:dev:     at /Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:2186:68
sanity:dev:     at new Promise (<anonymous>)
sanity:dev:     at Object.context (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:2186:27)
sanity:dev:     at Object.context (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:2026:58)
sanity:dev:     at prepareEsbuildOptimizerRun (file:///Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/dist/node/chunks/dep-68d1a114.js:46041:35)
sanity:dev: 
sanity:dev:   The plugin "vite:dep-pre-bundle" was triggered by this import
sanity:dev: 
sanity:dev:     ../../node_modules/@sanity/vision/lib/_chunks/SanityVision-0TYSjevX.js:2:42:
sanity:dev:       2 │ import { useTranslation, useClient } from 'sanity';
sanity:dev:         ╵                                           ~~~~~~~~
sanity:dev: 
sanity:dev: 1:29:08 PM [vite] error while updating dependencies:
sanity:dev: Error: Build failed with 4 errors:
sanity:dev: ../../node_modules/@sanity/vision/lib/_chunks/index-ShIdQoSo.js:3:22: ERROR: Could not resolve "sanity/router"
sanity:dev: ../../node_modules/vite/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "sanity". The package may have incorrect main/module/exports specified in its package.json.
sanity:dev: ../../node_modules/vite/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "sanity". The package may have incorrect main/module/exports specified in its package.json.
sanity:dev: ../../node_modules/vite/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "sanity". The package may have incorrect main/module/exports specified in its package.json.
sanity:dev:     at failureErrorWithLog (/Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:1649:15)
sanity:dev:     at /Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:1058:25
sanity:dev:     at /Users/flayks/Desktop/sanity-turborepo-bun/node_modules/vite/node_modules/esbuild/lib/main.js:1525:9
sanity:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by rexxars** [comment]
Bun (and npm) gets confused because in your `apps` folder you have a `sanity` directory, which has `sanity` as its name in `package.json`.

In the `<root>/apps/sanity` folder, it installs the correct dependency to the actual `sanity` npm module, whereas in the root of the project, the `sanity` dependency (`<root>/node_modules/sanity`) is a symlink to `<root>/apps/sanity`. Because `@sanity/vision` gets hoisted to the top level instead of being located inside of `<root>/apps/sanity`, it tries to resolve its `sanity` dependency using this sibling, which points to the workspace app instead of the actual npm module, which fails.

I would recommend you rename the `sanity` folder to `studio`, or `sanity-studio` or some such (make sure to update the `name` field in `package.json` to match!).

If you have any suggestions on how we (sanity) can help detect/prevent this situation, let us know!

**Comment by flayks** [comment]
Haaaa, that explains things! I didn't realize it would cause issues. Thank you for figuring this out @rexxars 🙏
