### ISSUE TITLE
Cannot start Studio since 3.26.0

### ISSUE THREAD

**Issue by flayks** [sanity-io/sanity#5569]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Since v3.26.0, it's impossible to start the Studio, I get this error:
```
$ sanity dev
The `sanity` module is not installed in current project
Project-specific commands not available until you run `bun install`

Error: Command "dev" is not available outside of a Sanity project context.
Run the command again within a Sanity project directory, where "sanity"
is installed as a dependency.
    at CommandRunner.runCommand (/opt/homebrew/lib/node_modules/@sanity/cli/lib/_chunks/cli-icdWEj-T.js:19282:28262)
    at Object.runCli (/opt/homebrew/lib/node_modules/@sanity/cli/lib/_chunks/cli-icdWEj-T.js:19288:38)
error: script "dev" exited with code 1
```

It works fine with 3.25.0 on the same exact setup.

**To Reproduce**

Install Sanity 3.26.0?

**Expected behavior**

It should run the Studio without throwing an error

**Which versions of Sanity are you using?**

```
The `sanity` module is not installed in current project
Project-specific commands not available until you run `npm install`
@sanity/cli (global)             3.26.0 (up to date)
@sanity/code-input                4.1.2 (up to date)
@sanity/eslint-config-studio      3.0.1 (up to date)
@sanity/vision                   3.26.0 (up to date)
sanity                        <missing> (latest: 3.26.0)
```

**What operating system are you using?**

macOS 14.2.1

**Which versions of Node.js / npm are you running?**

```
10.2.4
v20.11.0
```

**Additional context**

I'm running the project in a Turbo monorepo and Sanity inside `/apps/sanity-studio` and using Bun (1.0.25)

**Comment by flayks** [comment]
It seems to be fixed with v3.26.1
