### ISSUE TITLE
Can't use Sanity with hoisted dependencies

### ISSUE THREAD

**Issue by ryami333** [sanity-io/sanity#559]
When using Sanity in a monorepo with `yarn workspaces` When I run `yarn workspace foo sanity start` (or `cd packages/foo && yarn sanity start`) I get the following error:

```bash
yarn run v1.3.2
$ sanity start
✔ Checking configuration files...
(node:86739) DeprecationWarning: webpack: Using compiler.parser is deprecated.
Use compiler.plugin("compilation", function(compilation, data) {
  data.normalModuleFactory.plugin("parser", function(parser, options) { parser.plugin(/* ... */); });
}); instead. 
webpack building...
⠏ Compiling...TypeError: compiler.parser.evaluate is not a function
    at Parser.<anonymous> (/path/to/project/node_modules/webpack/lib/DefinePlugin.js:71:31)
    at Parser.applyPluginsBailResult1 (/path/to/project/node_modules/@sanity/server/node_modules/tapable/lib/Tapable.js:140:27)
    at Parser.<anonymous> (/path/to/project/node_modules/@sanity/server/node_modules/webpack/lib/Parser.js:253:25)
    at Parser.applyPluginsBailResult1 (/path/to/project/node_modules/@sanity/server/node_modules/tapable/lib/Tapable.js:140:27)
    at Parser.evaluateExpression (/path/to/project/node_modules/@sanity/server/node_modules/webpack/lib/Parser.js:1236:24)
    at Parser.<anonymous> (/path/to/project/node_modules/@sanity/server/node_modules/webpack/lib/Parser.js:70:17)
    at Parser.applyPluginsBailResult1 (/path/to/project/node_modules/@sanity/server/node_modules/tapable/lib/Tapable.js:140:27)
    at Parser.evaluateExpression (/path/to/project/node_modules/@sanity/server/node_modules/webpack/lib/Parser.js:1236:24)
    at Parser.<anonymous> (/path/to/project/node_modules/@sanity/server/node_modules/webpack/lib/Parser.js:70:17)
    at Parser.applyPluginsBailResult1 (/path/to/project/node_modules/@sanity/server/node_modules/tapable/lib/Tapable.js:140:27)
/path/to/project/node_modules/webpack/lib/NullFactory.js:9
	return callback();
	       ^

TypeError: callback is not a function
    at NullFactory.create (/path/to/project/node_modules/webpack/lib/NullFactory.js:9:9)
    at semaphore.acquire (/path/to/project/node_modules/@sanity/server/node_modules/webpack/lib/Compilation.js:242:13)
    at Semaphore.acquire (/path/to/project/node_modules/@sanity/server/node_modules/webpack/lib/util/Semaphore.js:16:4)
    at iteratorFactory (/path/to/project/node_modules/@sanity/server/node_modules/webpack/lib/Compilation.js:238:14)
    at /path/to/project/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/path/to/project/node_modules/async/dist/async.js:1055:9)
    at eachOf (/path/to/project/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/path/to/project/node_modules/async/dist/async.js:3158:5)
    at Compilation.addModuleDependencies (/path/to/project/node_modules/@sanity/server/node_modules/webpack/lib/Compilation.js:219:12)
    at Compilation.processModuleDependencies (/path/to/project/node_modules/@sanity/server/node_modules/webpack/lib/Compilation.js:204:8)
error Command failed with exit code 1.
```

This appears to be because there is some plugin resolution which incorrectly assumes that `node_modules` dependencies must always be in the same directory as `sanity.json`. See [this page](https://nodejs.org/api/modules.html) for more information about how Node resolves modules starting at the current directory, and recurses into it's parent directories.

**Comment by rexxars** [comment]
This is interesting. Any chance we could have a look at your directory structure?

**Comment by ryami333** [comment]
In my particular case, I'm using a typical `yarn workspaces` setup which looks something like this:

```
node_modules/
    @sanity/
        ...etc
    ...etc
packages/
    package-one/
        package.json
        sanity.json
        ...etc
    package-two/
        package.json
        ...etc
package.json
...etc
```

The workspaces feature hoists dependencies to that root-level `node_modules`, rather than `packages/project-one/node_modules`. On its face, this might seem like a bit of an edge-case, but hoisted node_modules resolution is not a yarn workspaces feature, it's a Node feature. If you do the following, _with or without yarn workspaces_, `foo` will correctly resolve from ancestral `node_modules` directories:
```jsx
const foo = require('@sanity/foo');
```

**Comment by ryami333** [comment]
It looks to me like you might need to use `require.resolve` in `resolvePlugins.js` to recursively check all ancestral `node_modules` directories for existence of the plugin, before falling back to the local `./plugins` directory, rather than using a fixed/hardcoded list of locations which only includes the local `node_modules` directory. Make sense?

**Comment by rexxars** [comment]
It might be that plugin resolving is broken with hoisted dependencies, but I can't see how that should cause `compiler.parser.evaluate is not a function` errors. Could there somehow be two versions of webpack installed? If not, could you check which version is actually present in `packages/package-one/node_modules/webpack/package.json`, or if that does not exist, `node_modules/webpack/package.json`?

**Comment by bjoerge** [comment]
Closing this due to inactivity. Feel free to open a new issue if this is still a problem.
