### ISSUE TITLE
Admin page goes to 404 not found

### ISSUE THREAD

**Issue by Wooody82** [sanity-io/sanity#6140]
I use sanity with astro latest versions. When we visit admin page as I use route path the admin page works but if we visit anything there and refresh the page it goes to 404. plus if we save any post now it save the post but it show blank white and error!

**To Reproduce**

1. Go to admin page
2. Click on click on anything
3. Refresh the page
4. See error 404 not found
5. if we save post we get this error in dev log
Uncaught Error: Sanity LocaleContext value missing. Is this hook being used outside LocaleContext.Provider?
    at useLocale (useLocale.ts:22:11)
    at useCurrentLocale (useLocale.ts:12:10)
    at useListFormat (useListFormat.ts:37:25)
    at Translate (Translate.tsx:112:22)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    

**Expected behavior**
The Admin page should work even if we refresh it.

**Which versions of Sanity are you using?**
@sanity/cli (global)                   3.36.1 (up to date)
@sanity/asset-utils                     1.3.0 (up to date)
@sanity/astro                           3.0.0 (up to date)
@sanity/document-internationalization   2.1.0 (up to date)
@sanity/google-maps-input               3.0.2 (up to date)
@sanity/image-url                       1.0.2 (up to date)
@sanity/types                          3.36.1 (up to date)
@sanity/vision                         3.36.1 (up to date)
sanity                                 3.36.1 (up to date)

**What operating system are you using?**
macOs 14.4 Beta (23E5180j)

**Which versions of Node.js / npm are you running?**
v18.18.2

**Comment by razvanmitre** [comment]
Looks like downgrading to sanity version `3.36.0` fixes the issue

**Comment by Wooody82** [comment]
Hi, 
3.36.0 fixes part of the issue.. When we save the post it works fine.. But if you refresh the page it still go to 404.

**Comment by Wooody82** [comment]
OK, The issue not with  **sanity": "^3.36.1"**
Its working fine when I downgrade @sanity/astro from **3.0.0** to **2.2.1** and its working fine with sanity 3.36.1

**Comment by Digitl-Alchemyst** [comment]
I faced a similar issue, though I'm not using Sanity Astro. Simply downgrading to Sanity and @sanity/vision versions 3.35.2 resolved the hook issue during saving. Interestingly, I figured out what caused the 404 error while writing this reply and fixed it for myself.

These were separate issues. The hook problem seems related to recent changes, possibly requiring a wrapper around the <NextStudio> component in pages.tsx within the Next.js App Router environment. I'm currently checking the docs for solutions.

The 404 error, on the other hand, was about pathing. While your setup might differ, I'm using the latest Next.js version. I had a similar issue due to incorrect file placement. For Next.js, files should be organized like this:



src
│── app
    │── (admin)
        │── studio
            │── [[...index]]

Placing both layout.tsx and page.tsx (or .js for JavaScript) in this structure resolved my 404 problems.

Hope this helps clarify things. Let me know if you need more info.

Side note I am also wondering if the directory mismatch was ultimately causing the issue related to the sanity hooks I will try updating again at some point and see if the issue returns.

**Comment by Digitl-Alchemyst** [comment]
The src directory is optional for next js just helps to organize things a big,
same with the (admin) directory in next js its a (directory) that doesn't appear in the pathing used for folder organization, in contrast I have a second folder in app (user) where all my front end code lives they share a globals.css file that lives in the app dir and the only other thing in the app dir is the API folder.
Just to clarify on the pathing

**Comment by Anonymous327** [comment]
Getting the same issue with 3.36.1. Goes back to normal when I switch back to 3.36.0.

**Comment by cngonzalez** [comment]
Hello all! The hook issue you were seeing was indeed a bug in 3.36.1. It's hopefully been resolved in 3.36.2. Thanks so much for reporting!

As to the original issue in this thread: @Wooody82  -- are you still seeing the 404 when you refresh? I suspect it may be a directory / routing issue as others have said, but it may be worth getting a better look at how your embedded Studio is set up.

**Comment by Wooody82** [comment]
Hi @cngonzalez :-)
Well Now I downgrade it to     **"sanity": "^3.36.0",  "@sanity/astro": "^3.0.0",**
- And I still getting 404 when I refresh for all pages but not for  /admin/
- When I save any post working fine and does not show 404.

For routing I am just using Astro and Sanity. And I have it as multi language..

Here sanity config:
```
export default defineConfig({
  name: "ProjectName",
  title: "ProjectTitle",
  projectId,
  dataset,
  plugins: [
    structureTool(),
    visionTool(),
    documentInternationalization({
      // Required configuration
      supportedLanguages: [
        { id: 'ar', title: 'Arabic' },
        { id: 'en', title: 'English' }
      ],
      schemaTypes: ['property'],
    }),
    googleMapsInput({
      apiKey: mapApi
    }),
    muxInput()
  ],
  schema: {
    types: schemaTypes,
  },
});
```

And here Astro Config:
```
export default defineConfig({
  adapter: netlify(),
  output: "hybrid",
  site:  "http://examplesite.com",
  base: "/",
  trailingSlash: "ignore",
  i18n: {
    defaultLocale: "en",
    locales: ["en", "ar"],   
    routing: {
      prefixDefaultLocale: true
    }
  },
  integrations: [
    react(),
    sitemap(),
    tailwind({
      config: {
        applyBaseStyles: false,
      },
    }),
    AutoImport({
      imports: [
        "@/shortcodes/Button",
        "@/shortcodes/Accordion",
        "@/shortcodes/Notice",
        "@/shortcodes/Video",
        "@/shortcodes/Youtube",
        "@/shortcodes/Tabs",
        "@/shortcodes/Tab",
      ],
    }),
    mdx(),
    sanity({
      projectId,
      dataset,
      studioBasePath: "/en/admin",
      useCdn: false,
      apiVersion: "2024-03-25"
    }),
  ],
  markdown: {
    remarkPlugins: [
      remarkToc,
      [
        remarkCollapse,
        {
          test: "Table of contents",
        },
      ],
    ],
    shikiConfig: {
      theme: "one-dark-pro",
      wrap: true,
    },
    extendDefaultPlugins: true,
  },
});
```

**Comment by Digitl-Alchemyst** [comment]
Can you put your project in a repo and share that?

**Comment by Wooody82** [comment]
Hi @Digitl-Alchemyst 
Here a repo with the issue 404 in admin if you refresh:
https://github.com/Wooody82/stellar-star

**Comment by Digitl-Alchemyst** [comment]
@Wooody82 It maybe my lack of knowledge of astro, But i do not see any set up code at all for the studio page. can you give me a brief run down of how you access the studio and where if any in the source code there is code related to the studio. 

So like i in Nextjs I define my route like this in the sanity config

//  Set the Studio URL Also used to configure edit intent links, for Presentation Mode
export const studioUrl = '/studio'

and call it in my config set up
export default defineConfig({
  basePath: studioUrl,

  name: 'CMS_Studio',
  title: title,

  projectId: projectId,
  dataset: dataset,
  apiVersion: apiVersion,
// Other settings

});

Then I have code in my page files at /studio to set it up

**Comment by Digitl-Alchemyst** [comment]
Fron there sanity provides a studio that we pass config to

import { NextStudio } from 'next-sanity/studio'
import config from '#/sanity.config'
export { viewport } from 'next-sanity/studio'

export default function StudioPage() {
  return <NextStudio config={config} />
}

This is provided by sanity docs or cli cant remember which, should be something similar for astro.

**Comment by MohammedAlasaad** [comment]
Hi @Digitl-Alchemyst 
Well:
1. we have sanity.config.ts there we have projectId and dataset with schema and more.
2. we have astro.config.mjs file. there we have integration and we have sanity there
3. when we run "npm run dev" we can access the studio from same server we run, so it will be for ex like: localhost:4321/en/admin
as we have defined the path in astro.config.mjs : studioBasePath: "/en/admin".

**Comment by Digitl-Alchemyst** [comment]
and the sanity astro packages build out the studio in the same way my next/sanity package does that I have to set up the little bit i did?

**Comment by Digitl-Alchemyst** [comment]
try removing the en/ prefix and see if that works

**Comment by Wooody82** [comment]
@Digitl-Alchemyst no that does not work .. I need /en/admin

**Comment by Wooody82** [comment]
The issue from @sanity/astro 3.0.0 .. I downgrade it to 2.2.1

And I need to change the import in config like this:
import {sanityIntegration as sanity} from "@sanity/astro";

instead of 
import sanity from "@sanity/astro";
