### ISSUE TITLE
Uncaught error: Sanity LocaleContext value missing. Is this hook being used outside LocaleContext.Provider?

### ISSUE THREAD

**Issue by PandaTech19** [sanity-io/sanity#6146]
This keeps happening to me when i want to publish something,

I've tried creating a New project by multiple ways using (NPM , YARN )

but it always gives me the same error 

Uncaught error: Sanity LocaleContext value missing. Is this hook being used outside LocaleContext.Provider?
https://stocks.sanity.studio/static/sanity-421c566d.js:82:41296
Error: Sanity LocaleContext value missing. Is this hook being used outside LocaleContext.Provider?
    at c6 (https://stocks.sanity.studio/static/sanity-421c566d.js:1520:2252)
    at Cd (https://stocks.sanity.studio/static/sanity-421c566d.js:1520:2181)
    at Um (https://stocks.sanity.studio/static/sanity-421c566d.js:1995:30)
    at ft (https://stocks.sanity.studio/static/sanity-421c566d.js:1995:2592)
    at rL (https://stocks.sanity.studio/static/sanity-421c566d.js:80:19575)
    at Lue (https://stocks.sanity.studio/static/sanity-421c566d.js:82:44188)
    at Pue (https://stocks.sanity.studio/static/sanity-421c566d.js:82:39891)
    at sVe (https://stocks.sanity.studio/static/sanity-421c566d.js:82:39814)
    at WS (https://stocks.sanity.studio/static/sanity-421c566d.js:82:39664)
    at MR (https://stocks.sanity.studio/static/sanity-421c566d.js:82:36021)

It goes away when i refresh the page but its Hella annoying and I've tried asking Chat GBT but it didn't have an answer.

if anyone ran by this error and tried to fix it please tell me .

**Comment by WebShapedBiz** [comment]
Same here, began with v3.36.0

**Comment by cngonzalez** [comment]
Hello! This was indeed a bug in 3.36.1. 3.36.2 was just released, which should hopefully resolve this error.

**Comment by WebShapedBiz** [comment]
Thank you @cngonzalez, everything works fine :+1:

**Comment by joshgeller** [comment]
I'm still getting this in 3.36.2.
