### ISSUE TITLE
Build fails updating from 3.29 to 3.36

### ISSUE THREAD

**Issue by Snugug** [sanity-io/sanity#6199]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

After upgrading from Sanity 3.29.1 to 3.36.3, changing nothing else in my codebase, I get the following error when running `sanity dev`:

```
TypeError: Cannot read properties of undefined (reading 'div')
    at Object.<anonymous> (~/dev/cms/node_modules/.pnpm/@sanity+ui@2.0.14_react-dom@18.2.0_react-is@18.2.0_react@18.2.0_styled-components@5.3.11/node_modules/@sanity/ui/src/core/primitives/label/label.tsx:27:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.newLoader [as .js] (~/dev/cms/node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.20.2/node_modules/esbuild-register/dist/node.js:2262:9)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (~/dev/cms/node_modules/.pnpm/sanity@3.36.3_react-dom@18.2.0_react@18.2.0_styled-components@5.3.11/node_modules/sanity/lib/_chunks-cjs/TransformPatches.js:4:137)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
Unhandled rejection: TypeError: Cannot read properties of undefined (reading 'div')
    at Object.<anonymous> (~/dev/cms/node_modules/.pnpm/@sanity+ui@2.0.14_react-dom@18.2.0_react-is@18.2.0_react@18.2.0_styled-components@5.3.11/node_modules/@sanity/ui/src/core/primitives/label/label.tsx:27:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.newLoader [as .js] (~/dev/cms/node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.20.2/node_modules/esbuild-register/dist/node.js:2262:9)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (~/dev/cms/node_modules/.pnpm/sanity@3.36.3_react-dom@18.2.0_react@18.2.0_styled-components@5.3.11/node_modules/sanity/lib/_chunks-cjs/TransformPatches.js:4:137)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
```

This appears to be an internal Sanity issue with some kind of breaking change between point releases.

**Expected behavior**

When upgrading a point release, I expect the build to not break on an internal step, or for the error path to clearly show where in my code is causing the problem.

**Which versions of Sanity are you using?**

Migrating from 3.29.1 to 3.36.3

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

9.5.1
v18.16.0

**Comment by tiansial** [comment]
getting the same on 3.36.3

**Comment by kmelve** [comment]
Can you try upgrade to `styled-components@6` ?

**Comment by Snugug** [comment]
> Can you try upgrade to `styled-components@6` ?

Yup, that seemed to fix it. I guess the styled component peer dependency https://github.com/sanity-io/sanity/blob/next/packages/sanity/package.json#L337C1-L337C38 should be updated (which is also possibly a breaking SEMVER change)

**Comment by mediabeastnz** [comment]
Updating styled-components worked for me :)
