### ISSUE TITLE
Cannot delete documents from a migration script

### ISSUE THREAD

**Issue by thobas-dnvgl** [sanity-io/sanity#6925]
**Describe the bug**

Running a migration to delete document. Output is fine when running in dry run but the migration fails when it's not a dry un.

**To Reproduce**

```migration.ts
import {defineMigration, delete_} from 'sanity/migrate'
 
export default defineMigration({
  title: 'Remove 30 and 90 days documents',
  documentTypes: ['duration'],
  migrate: {
    document(doc) {
      if (doc._id === 'duration-30-days' || doc._id === 'duration-90-days') {
        return delete_(doc._id)
      }
    },
  },
})
```

**Expected behavior**

The same result dry run or not:

Dry run 👇

```bash
sanity migration run 5-remove-30-and-90-days-documents --project XXX --dataset test 
Running migration "5-remove-30-and-90-days-documents" in dry mode

Project id:  XXX
Dataset:     test

 delete   duration  duration-30-days 

 delete   duration  duration-90-days 
```

**Current result**

```bash
sanity migration run 5-remove-30-and-90-days-documents --project XXX --dataset test --no-dry-run
 
Note: During migrations, your webhooks stay active.
To adjust them, launch the management interface with sanity manage, navigate to the API settings, and toggle the webhooks before and after the migration as needed.
 
? This migration will run on the test dataset in XXX project. Are you sure? Yes
⠸ Running migration "5-remove-30-and-90-days-documents" ...
 
  Project id: XXX
  Dataset: test
  Document type: duration
 
  14 documents processed…
  2 mutations generated…
  1 requests pending…
  0 transactions committed.
 
  » delete duration duration-90-days
HTTPError: [object Object]: undefined
    at assert2xx (YYY/node_modules/@sanity/migrate/src/fetch-utils/fetchStream.ts:25:11)
    at fetchStream (YYY/node_modules/@sanity/migrate/src/fetch-utils/fetchStream.ts:31:3)
    at fetchAsyncIterator (YYY/node_modules/@sanity/migrate/src/fetch-utils/fetchStream.ts:37:32)
    at submit (YYY/node_modules/@sanity/migrate/src/runner/run.ts:132:50)
    at async file:///YYY/node_modules/@sanity/migrate/node_modules/p-map/index.js:216:27
    at async [Symbol.asyncIterator] (file:///YYY/node_modules/@sanity/migrate/node_modules/p-map/index.js:244:34)
    at Object.run (YYY/node_modules/@sanity/migrate/src/runner/run.ts:143:20)
    at Object.action (YYY/node_modules/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts:204:5)
```

**Which versions of Sanity are you using?**

```
sanity versions
@sanity/cli (global) 3.45.0 (latest: 3.46.0)
@sanity/cli 3.46.0 (up to date)
@sanity/color 3.0.6 (up to date)
@sanity/color-input 3.1.1 (up to date)
@sanity/eslint-config-studio 4.0.0 (up to date)
@sanity/icons 2.11.8 (latest: 3.2.0)
@sanity/table 1.1.2 (up to date)
@sanity/ui 2.3.5 (up to date)
@sanity/util 3.46.0 (up to date)
@sanity/uuid 3.0.2 (up to date)
@sanity/vision 3.46.0 (up to date)
sanity 3.46.0 (up to date)
```

**What operating system are you using?**

Windows 11.

**Which versions of Node.js / npm are you running?**

```
npm -v && node -v
10.8.1
v20.14.0
```

**Comment by binoy14** [comment]
Hi @thobas-dnvgl sorry you are running into this issue. Could you upgrade to `v3.47.1` we have release a fix that logs proper error message instead of `[object Object]` and try re-running this migration and post the error message if it's still happening

**Comment by thobas-dnvgl** [comment]
I've run the migration script again on `v3.47.1` and the documents were successfully deleted. I know this version was only supposed to give better error messages, but I cannot investigate more than that. Let's consider it closed :).
