### ISSUE TITLE
Possible ESM issue when running sanity typegen extract

### ISSUE THREAD

**Issue by heggemsnes** [sanity-io/sanity#6998]
**Describe the bug**

We've setup a kinda config based routing system on Next.js (so we can use less time refactoring all our files when you change your preview...). We want to use some data from here to i.e. give a nice preview of the path in the slug or add a "copy" link to the frontend URL.

When doing this and running `cd sanity && dotenv -e ../.env -- sanity schema extract --path ../schema.json --enforce-required-fields` it fails and produces an error:

```
✖ Failed to extract schema, with enforced required fields

/project/workspace/node_modules/.pnpm/next-safe-action@7.0.2_next@14.2.1_react-dom@18.2.0_react@18.2.0_zod@3.23.8/node_modules/next-safe-action/dist/hooks.mjs:4
import { isNotFoundError } from "next/dist/client/components/not-found.js";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.newLoader [as .mjs] (/project/workspace/node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.21.5/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.<anonymous> (/project/workspace/app/client.component.tsx:2:27)
 ELIFECYCLE  Command failed with exit code 1.
```

Note that this seems to have started happening after we began to use `next-safe-action` so it might be the problem is there?

**To Reproduce**

1. Check[ reproduction here](https://codesandbox.io/p/devbox/sanity-recreate-w6ntpp?file=%2Fapp%2Fpage.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxmu4w4f00063b6jyv5dr6f3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxmu4w4f00023b6jksu5zc30%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxmu4w4f00043b6j47amlxko%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxmu5eup002g3b6jcriu3y9e%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxmu4w4f00053b6jj8jdyhvt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B56.2527876303549%252C43.7472123696451%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxmu4w4f00023b6jksu5zc30%2522%253A%257B%2522id%2522%253A%2522clxmu4w4f00023b6jksu5zc30%2522%252C%2522activeTabId%2522%253A%2522clxmuobhp00pf3b6j5hnln31g%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxmu4w4e00013b6jaj88ft4n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxmu5qu600023b6jmh788hcl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252F.pnpm%252Frxjs%2522%252C%2522id%2522%253A%2522clxmuobhp00pf3b6j5hnln31g%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clxmu4w4f00053b6jj8jdyhvt%2522%253A%257B%2522id%2522%253A%2522clxmu4w4f00053b6jj8jdyhvt%2522%252C%2522activeTabId%2522%253A%2522clxmu79dx005j3b6js06ijtjb%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clxmu79dx005j3b6js06ijtjb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clxmu4w4f00043b6j47amlxko%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxmu4w4f00033b6jbc1j6jn7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clxmu4w4f00043b6j47amlxko%2522%252C%2522activeTabId%2522%253A%2522clxmu4w4f00033b6jbc1j6jn7%2522%257D%252C%2522clxmu5eup002g3b6jcriu3y9e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxmu57x2002d3b6jzwsdm5ul%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxmu7ca8000fdgih3c186azv%2522%257D%255D%252C%2522id%2522%253A%2522clxmu5eup002g3b6jcriu3y9e%2522%252C%2522activeTabId%2522%253A%2522clxmu57x2002d3b6jzwsdm5ul%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
2. Run `pnpm typegen` in the console.

**Expected behavior**

Would hope that we can get it to work as the next-safe-actions is quite useful :)

**Which versions of Sanity are you using?**

@sanity/cli (global) 3.47.1 (up to date)
sanity 3.47.1 (up to date)

**What operating system are you using?**
Sandbox (?)

**Which versions of Node.js / npm are you running?**

9.8.1
v20.9.0

**Additional context**

In our actual project we are not getting this exact error but something similar:

```
/Users/sigurdheggemsnes/Documents/GitHub/home-start/node_modules/.pnpm/next-safe-action@7.0.2_next@14.2.3_react-dom@18.3.1_react@18.3.1_zod@3.23.8/node_modules/next-safe-action/dist/index.mjs:2
import { validate } from "@typeschema/main";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.newLoader [as .mjs] (~/Documents/GitHub/home-start/node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.21.4/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.<anonymous> (~/Documents/GitHub/home-start/src/server/actions/safe-action.ts:1:40)
    
```

**Comment by sgulseth** [comment]
Tested with the latest version of the cli, and it worked. This was probably resolved in a pr and didn't reference this issue:
```✓ Extracted schema to ../schema.json with enforced required fields
✓ Config loaded from undefined
✓ Schema loaded from ./schema.json
✓ Generated 12 schema types
✓ Generated 1 query type from 1 file out of 7 scanned files
✓ Formatted generated types with prettier
✓ Successfully generated types to ./sanity.types.ts```
