### ISSUE TITLE
Command failed with exit code 1 (EPERM): npx install-peerdeps --yarn next-sanity@9

### ISSUE THREAD

**Issue by lhoucinecherif** [sanity-io/sanity#7027]
**Describe the bug**

I'm encountering an issue while trying to initialize Sanity for a Next.js project. The install-peerdeps command fails with a permission error despite multiple attempts with different approaches. Here are the details:

**To Reproduce**

1.Install a next boilerplate
  `git clone https://github.com/next-enterprise.git`
  `cd next-enterprise`
  `yarn install --frozen-lockfile`
  
2. Install sanity over the next project
 ` npx sanity@latest init --env --create-project "Next.js Live Preview" --dataset production`
 
3. Answering CLI questions like this :
  -  Would you like to add configuration files for a Sanity project in this Next.js folder? Yes
  - Do you want to use TypeScript? Yes
  - Would you like an embedded Sanity Studio? Yes
  - What route do you want to use for the Studio? /studio
  - Select project template to use Clean project with no predefined schema types
  - Would you like to add the project ID and dataset to your .env file? Yes

**Expected behavior**

The command should init & install all necessary peer dependencies  for sanity inside the existing nextjs  project

**Which versions of Sanity are you using?**

sanity: command not found

**What operating system are you using?**

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

npm 10.8.1
node v20.15.0

**Additional context**

This is the last lines of the console output : 
```

install-peerdeps v3.0.3
Installing peerdeps for next-sanity@9.
yarn add next-sanity@9.4.2 @sanity/client@^6.20.1 @sanity/icons@^3.0.0 @sanity/types@^3.37.1 @sanity/ui@^2.0.11 next@^15.0.0 react@^19.0.0 sanity@^3.37.1 styled-components@^6.1

ERR undefined

Error: Command failed with exit code 1 (EPERM): npx install-peerdeps --yarn next-sanity@9
    at makeError$1 (~/.npm/_npx/7c099b67f9967cde/node_modules/@sanity/cli/lib/_chunks-cjs/cli.js:17897:32)
    at ~/.npm/_npx/7c099b67f9967cde/node_modules/@sanity/cli/lib/_chunks-cjs/cli.js:18238:29
    at async initSanity (~/.npm/_npx/7c099b67f9967cde/node_modules/@sanity/cli/lib/_chunks-cjs/cli.js:44389:110)

```

**Comment by juice49** [comment]
Hi @lhoucinecherif. Please can you double check the URL of the boilerplate you cloned? `https://github.com/next-enterprise.git` is not a valid GitHub repository.

**Comment by stijlfigurant** [comment]
Running into a similar problem.

Trying to port an exisiting next-js project to be using sanity. Have `"next": "^14.2.3",` in my package json

With yarn, running `npx install-peerdeps --yarn next-sanity` as mentioned on https://www.npmjs.com/package/next-sanity/v/4.1.5#yarn

Response: 

```
install-peerdeps v3.0.3
Installing peerdeps for next-sanity@latest.
yarn add next-sanity@9.4.3 @sanity/client@^6.20.1 @sanity/icons@^3.0.0 @sanity/types@^3.37.1 @sanity/ui@^2.0.11 next@^15.0.0 react@^19.0.0 sanity@^3.37.1 styled-components@^6.1

ERR undefined
```

The undefined error makes it hard to triage

**Comment by luizlevindiniz** [comment]
Yeah, I have gotten the same issue while following this sanity tutorial https://www.sanity.io/guides/nextjs-app-router-live-preview#46870b28c449

I've made some research and it seems that the root cause is a node issue, check those links:
https://github.com/nodejs/node/issues/52554
https://stackoverflow.com/questions/78420489/error-when-running-npm-script-with-yarn-err-spawn-einval

**Comment by RobertCekay** [comment]
its next v15

**Comment by kolkol69** [comment]
for me, installing deps manually fixes the problem

```
yarn add next-sanity@9.5.0 next@^15.0.0 react@^19.0.0 sanity@^3.57.4 @sanity/ui@^2.8.9 @sanity/icons@^3.4.0 @sanity/types@^3.57.4 @sanity/client@^6.21.3 styled-components@^6.1
```

**Comment by alandouglas96** [comment]
Same here, did everything as I always do:

First `npx create-next-app@latest`, cd into it and `pnpm create sanity@latest`. Then the same error appears. 

Error displays:
`Found: react@19.0.0-rc-66855b96-20241106` when it expects `react@"^18.3 || ^19.0.0-0"`. So it makes sense that manually installing `react@^19.0.0` fixes it!

**Comment by cngonzalez** [comment]
Hello all! We recently did some due diligence around our dependencies. Would you please let me know if you're still experiencing issues? If not, we can close this issue in the coming week. Thank you!

**Comment by bamofah** [comment]
Just tried it today and having the same issue 

project is a `next.js 15 and react 19 projcect`

then run this 

```
pm create sanity@latest -- --project <projectId> --dataset production --template blog --typescript --output-path studio-e
```

the got the following output 

```
install-peerdeps v3.0.3
ERR undefined

Error: Command failed with exit code 1 (EPERM): npx install-peerdeps --yarn next-sanity@9
    at error (~/.npm/_npx/67a0730928194b24/node_modules/@sanity/cli/lib/_chunks-cjs/cli.js:18524:32)
    at ~/.npm/_npx/67a0730928194b24/node_modules/@sanity/cli/lib/_chunks-cjs/cli.js:18926:31
    at async initSanity (~/.npm/_npx/67a0730928194b24/node_modules/@sanity/cli/lib/_chunks-cjs/cli.js:52933:130)
```

when I run that again I get the following 

```
 npx install-peerdeps --yarn next-sanity@latest
install-peerdeps v3.0.3
ERR undefined
```

**Comment by nathanhleung** [comment]
This was an issue on the `install-peerdeps` side. I just pushed a fix for Yarn users which is live in the latest release, v3.0.6.

**Comment by bjoerge** [comment]
Thank you @nathanhleung! Closing this issue then.

**Comment by bamofah** [comment]
@nathanhleung just tried it and I get the following output 

`install-peerdeps v3.0.6
ERR {"type":"error","data":"This project's package.json defines \"packageManager\": \"yarn@4.7.0\". However the current global version of Yarn is 1.22.22."}

Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.`

**Comment by nathanhleung** [comment]
> [@nathanhleung](https://github.com/nathanhleung) just tried it and I get the following output
> 
> `install-peerdeps v3.0.6 ERR {"type":"error","data":"This project's package.json defines "packageManager": "yarn@4.7.0". However the current global version of Yarn is 1.22.22."}
> 
> Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19. Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out [https://yarnpkg.com/corepack.`](https://yarnpkg.com/corepack.%60)

Hmm, what was the original command you ran? Was it `install-peerdeps next-sanity@latest`? The preferred usage is now `yarn dlx / pnpm dlx / npx install-peerdeps [args]` (prefixed with a call to the local package manager itself, as you ran afterwards), since this will default to using the local `packageManager` defined in `package.json`.

My hunch is that you might have Yarn 1.22.22 installed globally (try running `yarn --version` in your home directory, outside of any `npm` project) whereas `yarn@4.7.0` is the local package manager used by the project.

**Comment by nathanhleung** [comment]
@bamofah 

> [@nathanhleung](https://github.com/nathanhleung) just tried it and I get the following output
> 
> `install-peerdeps v3.0.6 ERR {"type":"error","data":"This project's package.json defines "packageManager": "yarn@4.7.0". However the current global version of Yarn is 1.22.22."}
> 
> Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19. Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out [https://yarnpkg.com/corepack.`](https://yarnpkg.com/corepack.%60)

Hmm, what was the original command you ran? Was it `install-peerdeps next-sanity@latest`? The preferred usage is now `yarn dlx / pnpm dlx / npx install-peerdeps [args]` (prefixed with a call to the local package manager itself, as you ran afterwards), since this will default to using the local `packageManager` defined in `package.json`.

My hunch is that you might have Yarn 1.22.22 installed globally (try running `yarn --version` in your home directory, outside of any `npm` project) whereas `yarn@4.7.0` is the local package manager used by the project.

**Comment by bamofah** [comment]
> peerdeps

Sorry for late reply missed the notification. when I ran `yarn --version` from anywhere (outside of the project) it giving me version `4.7.0`. honestly not sure what was going
