### ISSUE TITLE
Sanity 3.52.2 RollupError: "FieldPresenceWithOverlay" is not exported by "node_modules/sanity/lib/index.mjs" for sanity-plugin-icon-manager

### ISSUE THREAD

**Issue by mjablons** [sanity-io/sanity#7261]
**Describe the bug**

Latest version i.e. 3.52.2 breaks [sanity-plugin-icon-manager](https://github.com/williamiommi/sanity-plugin-icon-manager) plugin. Version earlier (i.e. 3.52.1) works fine with the plugin. 

```
$ sanity build 

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
✔ Clean output folder (5ms)
⠋ Build Sanity StudioThe CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
✖ Build Sanity Studio

RollupError: "FieldPresenceWithOverlay" is not exported by "node_modules/sanity/lib/index.mjs", imported by "node_modules/sanity-plugin-icon-manager/dist/index.esm.js".
    at error (file://~/project-name/sanity/node_modules/sanity/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file://~/project-name/sanity/node_modules/sanity/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file://~/project-name/sanity/node_modules/sanity/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file://~/project-name/sanity/node_modules/sanity/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at ReturnValueScope.findVariable (file://~/project-name/sanity/node_modules/sanity/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file://~/project-name/sanity/node_modules/sanity/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at Identifier.bind (file://~/project-name/sanity/node_modules/sanity/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
    at CallExpression.bind (file://~/project-name/sanity/node_modules/sanity/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at CallExpression.bind (file://~/project-name/sanity/node_modules/sanity/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
    at Property.bind (file://~/project-name/sanity/node_modules/sanity/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
```

**To Reproduce**
```
npm install sanity@3.52.2
npm install sanity-plugin-icon-manager
```

add to sanity.config.ts:
```
import {IconManager} from 'sanity-plugin-icon-manager'
// rest of the config
plugins: [IconManager({})],
// rest of the config
```
```
$ sanity build
```

**Expected behavior**

build without any error

**Which versions of Sanity are you using?**

3.52.2

**What operating system are you using?**

iOS 14.5

**Which versions of Node.js / npm are you running?**

10.2.3
v22.0.0

**Comment by stipsan** [comment]
Thanks for the report! I'll PR a fix 🙌
