### ISSUE TITLE
Validate/extract schema fails when there is a url import in `sanity.config.ts`

### ISSUE THREAD

**Issue by silvertech-daniel** [sanity-io/sanity#7602]
**Describe the bug**

Importing a theme from `https://themer.sanity.build/api/hues` in `sanity.config.ts`  causes an error like
```
Error: Failed to load configuration file ".../sanity.config.ts":
Cannot find module 'https://themer.sanity.build/api/hues?...'
Require stack:
- .../sanity.config.ts
- .../node_modules/sanity/lib/_chunks-cjs/getStudioWorkspaces.js
- .../node_modules/sanity/lib/_internal/cli/threads/extractSchema.js
    at Module._resolveFilename (.../node_modules/esbuild-register/dist/node.js:4794:36)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at Object.<anonymous> (.../sanity.config.ts:9:23)
    at Module._compile (.../node_modules/esbuild-register/dist/node.js:2258:26)
```

**Expected behavior**

- Avoid attempting to import urls when validating/extracting the schema
- Warn instead of error if an import fails during the schema validation/extraction
- Expose a way to configure the module loader

**Versions**
```
> npm -v
10.8.3
> node -v
v22.9.0
> npx sanity versions
@sanity/cli (global)    3.59.1 (up to date)
@sanity/asset-utils      1.3.0 (latest: 2.0.6)
@sanity/icons            3.4.0 (up to date)
@sanity/react-loader    1.10.7 (up to date)
@sanity/schema          3.59.1 (up to date)
@sanity/ui               2.8.9 (up to date)
@sanity/vision          3.59.1 (up to date)
@sanity/visual-editing  2.1.10 (up to date)
sanity                  3.59.1 (up to date)
```

**Comment by devinhalladay** [comment]
@silvertech-daniel did you find a workaround?

**Comment by silvertech-daniel** [comment]
@devinhalladay I got through this by vendoring the file

**Comment by domnantas** [comment]
I'm facing the same issue. Could you give more details about vendoring the file?

**Comment by silvertech-daniel** [comment]
@domnantas "vendoring" here means taking an external dependency and copying it into your own source code. For my case, I just made a new file and copy+pasted the content after opening the url in a browser. If your url import also imports other modules, you'd have to manually fix those. If the content of that external module is dynamic, you're out of luck with my workaround. That's why I haven't closed this bug yet.
