### ISSUE TITLE
Error when trying to deploy Sanity Studio

### ISSUE THREAD

**Issue by nalanart** [sanity-io/sanity#7869]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Hello, I'm following the Getting Started walkthrough for Sanity Studio and I'm on the last step which is deploying my Studio with Sanity. When running the command `npm run deploy`, I receive the following error:

```
name studio-studio-july % npm run deploy   

> studio-july@1.0.0 deploy
> sanity deploy

✅ Checking project info
? Select existing studio hostname name
ℹ Building with auto-updates enabled

Error: Failed to fetch remote version for https://sanity-cdn.com/v1/modules/sanity/default/%5E3.64.2/t1732367503: fetchFn is not a function
    at getRemoteResolvedVersion (~/studio-studio-july/node_modules/sanity/lib/_chunks-cjs/buildAction.js:138:11)
    at compareStudioDependencyVersions (~/studio-studio-july/node_modules/sanity/lib/_chunks-cjs/buildAction.js:146:35)
    at Object.buildSanityStudio (~/studio-studio-july/node_modules/sanity/lib/_chunks-cjs/buildAction.js:190:28)
    at async Object.deployStudioAction [as default] (~/studio-studio-july/node_modules/sanity/lib/_chunks-cjs/deployAction.js:51:25)
```

**To Reproduce**

Same steps as in the Getting Started section of Sanity Studio.
Error occurs when running `npm run deploy` on the last step.

**Expected behavior**

The command runs as expected and Studio gets deployed successfully

**Screenshots**

**Which versions of Sanity are you using?**

From my package.json: `"sanity": "^3.64.2",`

**What operating system are you using?**
MacOS

**Which versions of Node.js / npm are you running?**

8.19.4
v16.20.0

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by bjoerge** [comment]
Closing due to inactivity
