### ISSUE TITLE
Removing inline references in Portable Text causes the editor to crash.

### ISSUE THREAD

**Issue by dagstuan** [sanity-io/sanity#7963]
When using inline references in portable text. Removing one of them causes the editor to crash when clicking on another one. See attached video recording for a demonstration. If i click a reference, then remove it with `[backspace]`, the editor will crash when I click on the next reference.

https://github.com/user-attachments/assets/c932a02c-180d-43a9-b020-9e770c0befdf

The error printed is:

```
Error: Cannot resolve a DOM node from Slate node: {"_key":"void-child","_type":"span","text":"","marks":[]}
    at Object.toDOMNode (http://localhost:3000/_next/static/chunks/node_modules__pnpm_4206e6._.js:36582:19)
    at Object.toDOMPoint (http://localhost:3000/_next/static/chunks/node_modules__pnpm_4206e6._.js:36588:28)
    at Object.toDOMRange (http://localhost:3000/_next/static/chunks/node_modules__pnpm_4206e6._.js:36651:35)
    at Editable.useIsomorphicLayoutEffect.setDomSelection (http://localhost:3000/_next/static/chunks/e430c_slate-react_dist_index_es_ceed2f.js:1754:64)
    at Editable.useIsomorphicLayoutEffect (http://localhost:3000/_next/static/chunks/e430c_slate-react_dist_index_es_ceed2f.js:1772:17)
    at react-stack-bottom-frame (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:12452:22)
    at runWithFiberInDEV (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:631:20)
    at commitHookEffectListMount (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:5821:628)
    at commitHookLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:5809:60)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6153:30)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6228:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6194:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6228:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6228:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6194:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6194:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6228:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6152:17)
    at recursivelyTraverseLayoutEffects (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6645:105)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/2671e_next_dist_compiled_react-dom_478089._.js:6194:17)
```

**Comment by christianhg** [comment]
Hi there! I don't manage to reproduce this. Is it stil happening for you?

**Comment by dagstuan** [comment]
@christianhg I just checked, and no, I can't reproduce this anymore. It must have been fixed at some point. Thank you anyway! Closing this issue.
