### ISSUE TITLE
Crashing with "too many re-renders" on 3.68.0

### ISSUE THREAD

**Issue by dagstuan** [sanity-io/sanity#8097]
**Describe the bug**

After upgrading from 3.67.1 to 3.68.0 I get frequent crashes when I open documents in the Studio.

<img width="1322" alt="image" src="https://github.com/user-attachments/assets/fda354b3-88d0-4a7d-a6ce-62c240689633" />

The error is:

```
{
  "error": {
    "stack": "Error: Too many re-renders. React limits the number of renders to prevent an infinite loop.\n    at renderWithHooksAgain (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:3019:61)\n    at renderWithHooks (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:2983:28)\n    at updateFunctionComponent (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:4732:21)\n    at updateSimpleMemoComponent (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:4675:16)\n    at updateMemoComponent (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:4650:302)\n    at beginWork (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:5433:24)\n    at runWithFiberInDEV (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:631:20)\n    at performUnitOfWork (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:7955:97)\n    at workLoopSync (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:7847:40)\n    at renderRootSync (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:7830:13)\n    at performWorkOnRoot (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:7589:56)\n    at performWorkOnRootViaSchedulerTask (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_react-dom_5a548e._.js:8394:9)\n    at MessagePort.performWorkUntilDeadline (http://localhost:3000/_next/static/chunks/3d618_next_dist_compiled_f4c978._.js:2353:64)",
    "message": "Too many re-renders. React limits the number of renders to prevent an infinite loop.",
    "_componentStack": "\n    at http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:6484:316\n    at http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:6425:13\n    at GetFormValueProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:45608:312)\n    at DocumentLayout (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_pane_mjs_c177cd._.js:7088:237)\n    at CommentsAuthoringPathProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:51838:312)\n    at http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:54592:312\n    at CommentsDocumentLayoutInner (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:55216:312)\n    at CommentsDocumentLayout (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:55201:312)\n    at http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:54315:13\n    at CommentsProviderWrapper (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_pane_mjs_c177cd._.js:3189:312)\n    at http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:54544:312\n    at CommentsWrapper (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_pane_mjs_c177cd._.js:3174:312)\n    at ReferenceInputOptionsProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:12895:312)\n    at Memo(DocumentPaneProvider) (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_pane_mjs_c177cd._.js:7308:13)\n    at DocumentPaneInner (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_pane_mjs_c177cd._.js:7949:312)\n    at CopyPasteProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:86669:30)\n    at SourceProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:49663:312)\n    at http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_pane_mjs_c177cd._.js:7936:312\n    at Suspense (<anonymous>)\n    at PaneRouterProvider (http://localhost:3000/_next/static/chunks/08b5e__pnpm_a84783._.js:103:312)\n    at push.[project]/node_modules/.pnpm/sanity@3.68.0_@emotion+is-prop-valid@1.2.2_@types+babel__core@7.20.5_@types+node@22.10.2_@typ_2fz77jbex65uw4jopn5gcomuyi/node_modules/sanity/lib/_chunks-es/index3.mjs [app-client] (ecmascript)._b (http://localhost:3000/_next/static/chunks/08b5e__pnpm_a84783._.js:976:312)\n    at div (<anonymous>)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at ForwardRef(Box) (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:7354:312)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at ot (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7636:364)\n    at ThemeProvider (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:6036:312)\n    at ThemeColorProvider (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:6086:312)\n    at ForwardRef(Card) (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:8140:312)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at PaneLayout (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_pane_mjs_c177cd._.js:2344:312)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at PortalProvider (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:9532:312)\n    at http://localhost:3000/_next/static/chunks/08b5e__pnpm_a84783._.js:1179:312\n    at StructureToolProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_pane_mjs_c177cd._.js:13659:34)\n    at SourceProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:49663:312)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:9250:9)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_db3d6b._.js:196:312)\n    at StructureToolBoundary (http://localhost:3000/_next/static/chunks/08b5e__pnpm_a84783._.js:1276:312)\n    at StudioActiveToolLayout (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:81267:312)\n    at div (<anonymous>)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at ForwardRef(Box) (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:7354:312)\n    at div (<anonymous>)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at ForwardRef(Box) (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:7354:312)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at ForwardRef(Flex) (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:7622:312)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at TasksStudioActiveToolLayoutInner (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:76291:312)\n    at TasksStudioActiveToolLayout (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:76327:312)\n    at Suspense (<anonymous>)\n    at RouteScope (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_b43f83._.js:875:312)\n    at div (<anonymous>)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at ForwardRef(Box) (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:7354:312)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at ot (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7636:364)\n    at ThemeProvider (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:6036:312)\n    at ThemeColorProvider (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:6086:312)\n    at ForwardRef(Card) (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:8140:312)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:9250:9)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_db3d6b._.js:196:312)\n    at StudioErrorBoundary (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:82717:312)\n    at div (<anonymous>)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at ForwardRef(Box) (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:7354:312)\n    at O (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7697:10)\n    at ForwardRef(Flex) (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:7622:312)\n    at StudioLayoutComponent (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:82877:312)\n    at SanityCreateConfigProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:58184:312)\n    at CreateIntegrationWrapper (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:58210:312)\n    at SchedulePublishingUpsellProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:66947:312)\n    at ConditionalWrapper (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_db3d6b._.js:52:31)\n    at SchedulePublishingStudioLayoutInner (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:71170:312)\n    at ScheduledPublishingEnabledProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:66182:312)\n    at SchedulePublishingStudioLayout (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:71191:312)\n    at TasksNavigationProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:71385:312)\n    at TasksProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:71710:312)\n    at TasksUpsellProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:71753:312)\n    at ConditionalWrapper (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_db3d6b._.js:52:31)\n    at AddonDatasetProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:77354:312)\n    at TasksStudioLayoutInner (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:76346:312)\n    at TasksEnabledProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:71235:312)\n    at TasksStudioLayout (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:76370:312)\n    at CommentsUpsellProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:55078:312)\n    at ConditionalWrapper (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_db3d6b._.js:52:31)\n    at CommentsOnboardingProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:54570:312)\n    at AddonDatasetProviderInner (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:77258:13)\n    at AddonDatasetProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:77354:312)\n    at CommentsStudioLayout (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:56775:312)\n    at layout (http://localhost:3000/_next/static/chunks/e712d_@sanity_document-internationalization_dist_index_mjs_193d40._.js:4796:34)\n    at StudioLayout (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:82871:312)\n    at StudioAnnouncementsProviderInner (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:87650:312)\n    at StudioAnnouncementsProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:87778:312)\n    at ResourceCacheProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:40482:312)\n    at PackageVersionStatusProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:87107:312)\n    at I18nextProvider (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:15922:11)\n    at Suspense (<anonymous>)\n    at LocaleProviderBase (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:4691:312)\n    at LocaleProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:4681:312)\n    at TelemetryProvider (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:42578:11)\n    at StudioTelemetryProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:87813:20)\n    at RouterProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_b43f83._.js:803:312)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:9250:9)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_db3d6b._.js:196:312)\n    at WorkspaceRouterProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:88884:312)\n    at SourceProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:49663:312)\n    at WorkspaceProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:15058:312)\n    at WorkspaceLoader (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:89048:312)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:9250:9)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_db3d6b._.js:196:312)\n    at WorkspaceLoaderBoundary (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:89072:312)\n    at AuthBoundary (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:87001:312)\n    at UserColorManagerProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:5312:312)\n    at LayerProvider (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:9377:312)\n    at ot (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7636:364)\n    at ThemeProvider (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:6036:312)\n    at StudioThemeProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:88627:312)\n    at RouterHistoryProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:77063:312)\n    at http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:77075:404\n    at ActiveWorkspaceMatcher (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:77191:312)\n    at WorkspacesProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:77043:312)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:9250:9)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/1f820_sanity_lib__chunks-es_db3d6b._.js:196:312)\n    at StudioErrorBoundary (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:82717:312)\n    at ToastProvider (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:14127:312)\n    at ot (http://localhost:3000/_next/static/chunks/08b5e__pnpm_1467d7._.js:7636:364)\n    at ThemeProvider (http://localhost:3000/_next/static/chunks/8a97e_@sanity_ui_dist_53e919._.js:6036:312)\n    at ColorThemeProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:77389:312)\n    at ColorSchemeLocalStorageProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:77415:312)\n    at ColorSchemeProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:77399:312)\n    at StudioProvider (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:89095:312)\n    at Studio (http://localhost:3000/_next/static/chunks/1f820_sanity_lib_index_mjs_9db085._.js:89168:312)\n    at div (<anonymous>)\n    at NextStudioLayoutComponent (http://localhost:3000/_next/static/chunks/08b5e__pnpm_194dd5._.js:22:38)\n    at StyledComponentsRegistry (http://localhost:3000/_next/static/chunks/08b5e__pnpm_194dd5._.js:134:37)\n    at NextStudioComponent (http://localhost:3000/_next/static/chunks/08b5e__pnpm_194dd5._.js:160:32)\n    at Suspense (<anonymous>)\n    at NextStudioLazyClientComponent (<anonymous>)\n    at InnerLayoutRouter (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:279:11)\n    at RedirectErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:4643:9)\n    at RedirectBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:4651:11)\n    at HTTPAccessFallbackBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:6092:11)\n    at LoadingBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:375:11)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:3721:11)\n    at InnerScrollAndFocusHandler (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:188:9)\n    at ScrollAndFocusHandler (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:265:11)\n    at RenderFromTemplateContext (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:513:44)\n    at OuterLayoutRouter (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:411:11)\n    at InnerLayoutRouter (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:279:11)\n    at RedirectErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:4643:9)\n    at RedirectBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:4651:11)\n    at HTTPAccessFallbackBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:6092:11)\n    at LoadingBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:375:11)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:3721:11)\n    at InnerScrollAndFocusHandler (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:188:9)\n    at ScrollAndFocusHandler (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:265:11)\n    at RenderFromTemplateContext (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:513:44)\n    at OuterLayoutRouter (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:411:11)\n    at body (<anonymous>)\n    at html (<anonymous>)\n    at RootLayout [Server] (<anonymous>)\n    at InnerLayoutRouter (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:279:11)\n    at RedirectErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:4643:9)\n    at RedirectBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:4651:11)\n    at HTTPAccessFallbackBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:6092:11)\n    at LoadingBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:375:11)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:3721:11)\n    at InnerScrollAndFocusHandler (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:188:9)\n    at ScrollAndFocusHandler (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:265:11)\n    at RenderFromTemplateContext (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:513:44)\n    at OuterLayoutRouter (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:411:11)\n    at InnerLayoutRouter (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:279:11)\n    at RedirectErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:4643:9)\n    at RedirectBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:4651:11)\n    at HTTPAccessFallbackErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:6084:9)\n    at HTTPAccessFallbackBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:6092:11)\n    at LoadingBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:375:11)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:3721:11)\n    at InnerScrollAndFocusHandler (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:188:9)\n    at ScrollAndFocusHandler (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:265:11)\n    at RenderFromTemplateContext (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:513:44)\n    at OuterLayoutRouter (http://localhost:3000/_next/static/chunks/3d618_next_dist_d14b89._.js:411:11)\n    at RedirectErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:4643:9)\n    at RedirectBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:4651:11)\n    at HTTPAccessFallbackErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:6084:9)\n    at HTTPAccessFallbackBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:6092:11)\n    at DevRootHTTPAccessFallbackBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:6161:11)\n    at ReactDevOverlay (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:13124:9)\n    at HotReload (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:13802:11)\n    at Router (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:14148:11)\n    at ErrorBoundaryHandler (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:3676:9)\n    at ErrorBoundary (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:3721:11)\n    at AppRouter (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:14522:11)\n    at ServerRoot (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:17361:46)\n    at Root (http://localhost:3000/_next/static/chunks/3d618_next_dist_client_45ec7b._.js:17380:11)"
  },
  "eventId": null
}
```

**To Reproduce**

Upgrade to 3.68.0, open a document in the studio.

**Expected behavior**

No crash. Downgrading back to 3.67.1 yields no crash.

**Comment by stipsan** [comment]
Can you give https://github.com/sanity-io/sanity/releases/tag/v3.68.1 a try and tell us if it resolves it for you?

**Comment by dagstuan** [comment]
@stipsan: works fine on 3.68.1! Thanks for the quick fix! ❤️
